apiVersion: v1
kind: Service
metadata:
  name: {{ include "content-service.fullname" . }}
  labels:
    app: {{ include "content-service.name" . }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app: {{ include "content-service.name" . }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      name: http
    - port: {{ .Values.service.metricsPort }}
      targetPort: metrics
      name: metrics

