server:
  port: 8081

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/identity
    username: identity
    password: identity
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
  flyway:
    enabled: true
  redis:
    host: localhost
    port: 6379

security:
  jwt:
    issuer: suuupra-identity
    audience: suuupra-api
    access-ttl-seconds: 900
    refresh-ttl-seconds: 2592000 # 30 days
    # ES256 keys: provide PEM via env/secret manager in non-dev
    ec:
      private-key-pem: ""
      public-key-pem: ""

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
