groups:
  - name: content-service-alerts
    rules:
      # Service availability
      - alert: ContentServiceDown
        expr: up{job="content-service"} == 0
        for: 1m
        labels:
          severity: critical
          service: content-service
        annotations:
          summary: "Content Service is down"
          description: "Content Service has been down for more than 1 minute"
          runbook_url: "https://wiki.suuupra.com/runbooks/content-service-down"

      # High error rate
      - alert: HighErrorRate
        expr: |
          (
            sum(rate(content_http_requests_total{status_code=~"5.."}[5m])) /
            sum(rate(content_http_requests_total[5m]))
          ) * 100 > 5
        for: 5m
        labels:
          severity: critical
          service: content-service
        annotations:
          summary: "High error rate detected"
          description: "Error rate is {{ $value }}% for the last 5 minutes"
          runbook_url: "https://wiki.suuupra.com/runbooks/high-error-rate"

      # High response time
      - alert: HighResponseTime
        expr: |
          histogram_quantile(0.99, 
            sum(rate(content_http_request_duration_seconds_bucket[5m])) by (le)
          ) > 0.5
        for: 5m
        labels:
          severity: warning
          service: content-service
        annotations:
          summary: "High response time detected"
          description: "P99 response time is {{ $value }}s for the last 5 minutes"
          runbook_url: "https://wiki.suuupra.com/runbooks/high-latency"

      # Upload failure rate
      - alert: HighUploadFailureRate
        expr: |
          (
            sum(rate(content_uploads_total{status="failed"}[5m])) /
            sum(rate(content_uploads_total[5m]))
          ) * 100 > 5
        for: 5m
        labels:
          severity: warning
          service: content-service
        annotations:
          summary: "High upload failure rate"
          description: "Upload failure rate is {{ $value }}% for the last 5 minutes"
          runbook_url: "https://wiki.suuupra.com/runbooks/upload-failures"

      # Search latency
      - alert: HighSearchLatency
        expr: |
          histogram_quantile(0.99,
            sum(rate(content_search_duration_seconds_bucket[5m])) by (le)
          ) > 0.2
        for: 5m
        labels:
          severity: warning
          service: content-service
        annotations:
          summary: "High search latency"
          description: "P99 search latency is {{ $value }}s for the last 5 minutes"
          runbook_url: "https://wiki.suuupra.com/runbooks/search-performance"

      # Elasticsearch sync lag
      - alert: HighElasticsearchSyncLag
        expr: avg(content_elasticsearch_sync_lag_seconds) > 300
        for: 5m
        labels:
          severity: warning
          service: content-service
        annotations:
          summary: "High Elasticsearch sync lag"
          description: "Elasticsearch sync lag is {{ $value }}s (>5 minutes)"
          runbook_url: "https://wiki.suuupra.com/runbooks/es-sync-lag"

      # Database connection issues
      - alert: DatabaseConnectionIssues
        expr: |
          histogram_quantile(0.95,
            sum(rate(content_database_query_duration_seconds_bucket[5m])) by (le)
          ) > 1
        for: 5m
        labels:
          severity: warning
          service: content-service
        annotations:
          summary: "Database performance degradation"
          description: "P95 database query time is {{ $value }}s for the last 5 minutes"
          runbook_url: "https://wiki.suuupra.com/runbooks/database-performance"

      # Memory usage
      - alert: HighMemoryUsage
        expr: |
          (
            process_resident_memory_bytes{job="content-service"} /
            (1024 * 1024 * 1024)
          ) > 2
        for: 10m
        labels:
          severity: warning
          service: content-service
        annotations:
          summary: "High memory usage"
          description: "Memory usage is {{ $value }}GB for the last 10 minutes"
          runbook_url: "https://wiki.suuupra.com/runbooks/memory-usage"

      # CPU usage
      - alert: HighCPUUsage
        expr: |
          rate(process_cpu_seconds_total{job="content-service"}[5m]) * 100 > 80
        for: 10m
        labels:
          severity: warning
          service: content-service
        annotations:
          summary: "High CPU usage"
          description: "CPU usage is {{ $value }}% for the last 10 minutes"
          runbook_url: "https://wiki.suuupra.com/runbooks/cpu-usage"

      # Disk space (if applicable)
      - alert: LowDiskSpace
        expr: |
          (
            node_filesystem_avail_bytes{mountpoint="/"} /
            node_filesystem_size_bytes{mountpoint="/"}
          ) * 100 < 10
        for: 5m
        labels:
          severity: critical
          service: content-service
        annotations:
          summary: "Low disk space"
          description: "Disk space is {{ $value }}% available"
          runbook_url: "https://wiki.suuupra.com/runbooks/disk-space"

      # WebSocket connection issues
      - alert: WebSocketConnectionDrop
        expr: |
          (
            sum(content_websocket_connections) < 
            (sum(content_websocket_connections offset 5m) * 0.5)
          ) and sum(content_websocket_connections offset 5m) > 10
        for: 2m
        labels:
          severity: warning
          service: content-service
        annotations:
          summary: "WebSocket connection drop"
          description: "WebSocket connections dropped by more than 50%"
          runbook_url: "https://wiki.suuupra.com/runbooks/websocket-issues"

      # Job processing failures
      - alert: HighJobFailureRate
        expr: |
          (
            sum(rate(content_jobs_processed_total{status="failure"}[5m])) /
            sum(rate(content_jobs_processed_total[5m]))
          ) * 100 > 10
        for: 5m
        labels:
          severity: warning
          service: content-service
        annotations:
          summary: "High background job failure rate"
          description: "Job failure rate is {{ $value }}% for the last 5 minutes"
          runbook_url: "https://wiki.suuupra.com/runbooks/job-failures"

  - name: content-service-slos
    rules:
      # SLO: 99.9% availability
      - alert: SLOAvailabilityBreach
        expr: |
          (
            1 - (
              sum(rate(content_http_requests_total{status_code=~"5.."}[30m])) /
              sum(rate(content_http_requests_total[30m]))
            )
          ) * 100 < 99.9
        for: 2m
        labels:
          severity: critical
          service: content-service
          slo: availability
        annotations:
          summary: "SLO availability breach"
          description: "Availability SLO (99.9%) breached: {{ $value }}%"
          runbook_url: "https://wiki.suuupra.com/runbooks/slo-breach"

      # SLO: P95 latency < 200ms
      - alert: SLOLatencyBreach
        expr: |
          histogram_quantile(0.95,
            sum(rate(content_http_request_duration_seconds_bucket[30m])) by (le)
          ) * 1000 > 200
        for: 5m
        labels:
          severity: warning
          service: content-service
          slo: latency
        annotations:
          summary: "SLO latency breach"
          description: "P95 latency SLO (200ms) breached: {{ $value }}ms"
          runbook_url: "https://wiki.suuupra.com/runbooks/slo-breach"

      # SLO: Search latency < 200ms
      - alert: SLOSearchLatencyBreach
        expr: |
          histogram_quantile(0.95,
            sum(rate(content_search_duration_seconds_bucket[30m])) by (le)
          ) * 1000 > 200
        for: 5m
        labels:
          severity: warning
          service: content-service
          slo: search-latency
        annotations:
          summary: "Search latency SLO breach"
          description: "Search P95 latency SLO (200ms) breached: {{ $value }}ms"
          runbook_url: "https://wiki.suuupra.com/runbooks/slo-breach"
