groups:
  - name: content-service-alerts
    interval: 30s
    rules:
      - alert: HighUploadFailureRate
        expr: increase(content_uploads_total{operation="complete",status="failure"}[5m]) > 5
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "High upload failure rate"
          description: "More than 5 failed uploads in 5 minutes"

      - alert: HighSearchLatencyP99
        expr: histogram_quantile(0.99, sum(rate(content_http_request_duration_seconds_bucket{route="/search"}[5m])) by (le)) > 0.2
        for: 5m
        labels:
          severity: critical
        annotations:
          summary: "Search p99 latency above 200ms"
          description: "p99 search latency exceeded 200ms for 5 minutes"

      - alert: HighIndexingLag
        expr: increase(content_indexing_dlq_total[5m]) > 0
        for: 10m
        labels:
          severity: warning
        annotations:
          summary: "Indexing lag detected (DLQ)"
          description: "Elasticsearch sync worker is adding items to DLQ"
