version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    environment:
      - POSTGRES_DB=mass_live_test_db
      - POSTGRES_USER=massuser
      - POSTGRES_PASSWORD=masspass
    ports:
      - "5434:5432"
    tmpfs:
      - /var/lib/postgresql/data
    networks:
      - test-network

  redis:
    image: redis:7-alpine
    ports:
      - "6381:6379"
    command: redis-server --appendonly no --save ""
    tmpfs:
      - /data
    networks:
      - test-network

  minio:
    image: minio/minio:latest
    ports:
      - "9002:9000"
      - "9003:9001"
    environment:
      - MINIO_ROOT_USER=minioadmin
      - MINIO_ROOT_PASSWORD=minioadmin
    command: server /data --console-address ":9001"
    tmpfs:
      - /data
    networks:
      - test-network

  # Test RTMP server
  rtmp-test:
    image: tiangolo/nginx-rtmp
    ports:
      - "1936:1935"
    volumes:
      - ./test-rtmp.conf:/etc/nginx/nginx.conf:ro
      - /tmp/test-streams:/tmp/hls
    networks:
      - test-network

networks:
  test-network:
    driver: bridge
