apiVersion: v1
kind: ConfigMap
metadata:
  name: commerce-config
  namespace: commerce
  labels:
    app: commerce-service
    version: v1
data:
  # Application Configuration
  APP_NAME: "commerce-service"
  APP_VERSION: "1.0.0"
  APP_ENV: "production"
  
  # Server Configuration
  HOST: "0.0.0.0"
  PORT: "8084"
  WORKERS: "4"
  
  # Database Configuration
  DB_HOST: "postgres-service"
  DB_PORT: "5432"
  DB_NAME: "commerce_db"
  DB_POOL_SIZE: "20"
  DB_MAX_OVERFLOW: "30"
  DB_POOL_TIMEOUT: "30"
  DB_POOL_RECYCLE: "3600"
  
  # Redis Configuration
  REDIS_HOST: "redis-service"
  REDIS_PORT: "6379"
  REDIS_DB: "0"
  REDIS_MAX_CONNECTIONS: "50"
  REDIS_SOCKET_TIMEOUT: "5"
  REDIS_SOCKET_CONNECT_TIMEOUT: "5"
  
  # Event Bus Configuration
  EVENT_BUS_TYPE: "redis"
  EVENT_BUS_BATCH_SIZE: "100"
  EVENT_BUS_FLUSH_INTERVAL: "1000"
  
  # Logging Configuration
  LOG_LEVEL: "INFO"
  LOG_FORMAT: "json"
  LOG_OUTPUT: "stdout"
  
  # Metrics Configuration
  METRICS_ENABLED: "true"
  METRICS_PORT: "9090"
  METRICS_PATH: "/metrics"
  
  # Health Check Configuration
  HEALTH_CHECK_ENABLED: "true"
  HEALTH_CHECK_PATH: "/health"
  HEALTH_CHECK_INTERVAL: "30"
  
  # Security Configuration
  CORS_ENABLED: "true"
  CORS_ORIGINS: "*"
  RATE_LIMIT_ENABLED: "true"
  RATE_LIMIT_REQUESTS: "1000"
  RATE_LIMIT_WINDOW: "3600"
  
  # External Services Configuration
  IDENTITY_SERVICE_URL: "http://identity-service:8080"
  PAYMENT_SERVICE_URL: "http://payment-service:8085"
  NOTIFICATION_SERVICE_URL: "http://notification-service:8086"
  SHIPPING_SERVICE_URL: "http://shipping-service:8087"
  
  # Feature Flags
  ENABLE_SAGA_ORCHESTRATION: "true"
  ENABLE_EVENT_SOURCING: "true"
  ENABLE_CQRS: "true"
  ENABLE_INVENTORY_MANAGEMENT: "true"
  ENABLE_ORDER_CANCELLATION: "true"
  ENABLE_SHIPPING_INTEGRATION: "true"
  ENABLE_NOTIFICATION_INTEGRATION: "true"
  
  # Performance Configuration
  MAX_REQUEST_SIZE: "10485760"  # 10MB
  REQUEST_TIMEOUT: "60"
  KEEP_ALIVE_TIMEOUT: "5"
  MAX_CONNECTIONS: "1000"
  
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: commerce-config-staging
  namespace: commerce-staging
  labels:
    app: commerce-service
    version: v1
    environment: staging
data:
  # Application Configuration
  APP_NAME: "commerce-service"
  APP_VERSION: "1.0.0"
  APP_ENV: "staging"
  
  # Server Configuration
  HOST: "0.0.0.0"
  PORT: "8084"
  WORKERS: "2"
  
  # Database Configuration
  DB_HOST: "postgres-staging-service"
  DB_PORT: "5432"
  DB_NAME: "commerce_staging_db"
  DB_POOL_SIZE: "10"
  DB_MAX_OVERFLOW: "15"
  DB_POOL_TIMEOUT: "30"
  DB_POOL_RECYCLE: "3600"
  
  # Redis Configuration
  REDIS_HOST: "redis-staging-service"
  REDIS_PORT: "6379"
  REDIS_DB: "1"
  REDIS_MAX_CONNECTIONS: "25"
  REDIS_SOCKET_TIMEOUT: "5"
  REDIS_SOCKET_CONNECT_TIMEOUT: "5"
  
  # Event Bus Configuration
  EVENT_BUS_TYPE: "redis"
  EVENT_BUS_BATCH_SIZE: "50"
  EVENT_BUS_FLUSH_INTERVAL: "2000"
  
  # Logging Configuration
  LOG_LEVEL: "DEBUG"
  LOG_FORMAT: "json"
  LOG_OUTPUT: "stdout"
  
  # Metrics Configuration
  METRICS_ENABLED: "true"
  METRICS_PORT: "9090"
  METRICS_PATH: "/metrics"
  
  # Health Check Configuration
  HEALTH_CHECK_ENABLED: "true"
  HEALTH_CHECK_PATH: "/health"
  HEALTH_CHECK_INTERVAL: "30"
  
  # Security Configuration
  CORS_ENABLED: "true"
  CORS_ORIGINS: "*"
  RATE_LIMIT_ENABLED: "false"
  RATE_LIMIT_REQUESTS: "100"
  RATE_LIMIT_WINDOW: "3600"
  
  # External Services Configuration
  IDENTITY_SERVICE_URL: "http://identity-staging-service:8080"
  PAYMENT_SERVICE_URL: "http://payment-staging-service:8085"
  NOTIFICATION_SERVICE_URL: "http://notification-staging-service:8086"
  SHIPPING_SERVICE_URL: "http://shipping-staging-service:8087"
  
  # Feature Flags
  ENABLE_SAGA_ORCHESTRATION: "true"
  ENABLE_EVENT_SOURCING: "true"
  ENABLE_CQRS: "true"
  ENABLE_INVENTORY_MANAGEMENT: "true"
  ENABLE_ORDER_CANCELLATION: "true"
  ENABLE_SHIPPING_INTEGRATION: "false"  # Disabled in staging
  ENABLE_NOTIFICATION_INTEGRATION: "true"
  
  # Performance Configuration
  MAX_REQUEST_SIZE: "5242880"  # 5MB
  REQUEST_TIMEOUT: "30"
  KEEP_ALIVE_TIMEOUT: "5"
  MAX_CONNECTIONS: "500"
