apiVersion: v1
kind: Secret
metadata:
  name: commerce-secrets
  namespace: commerce
  labels:
    app: commerce-service
    version: v1
type: Opaque
stringData:
  # Database Credentials
  DB_USERNAME: "commerce_user"
  DB_PASSWORD: "your_secure_db_password_here"
  
  # Redis Password
  REDIS_PASSWORD: "your_secure_redis_password_here"
  
  # JWT Configuration
  JWT_SECRET_KEY: "your_jwt_secret_key_here"
  JWT_ALGORITHM: "HS256"
  JWT_ACCESS_TOKEN_EXPIRE_MINUTES: "30"
  JWT_REFRESH_TOKEN_EXPIRE_DAYS: "7"
  
  # External Service API Keys
  STRIPE_SECRET_KEY: "sk_live_your_stripe_secret_key"
  STRIPE_WEBHOOK_SECRET: "whsec_your_stripe_webhook_secret"
  PAYPAL_CLIENT_ID: "your_paypal_client_id"
  PAYPAL_CLIENT_SECRET: "your_paypal_client_secret"
  
  # Shipping Service Keys
  FEDEX_API_KEY: "your_fedex_api_key"
  FEDEX_ACCOUNT_NUMBER: "your_fedex_account"
  FEDEX_METER_NUMBER: "your_fedex_meter"
  UPS_API_KEY: "your_ups_api_key"
  UPS_USERNAME: "your_ups_username"
  UPS_PASSWORD: "your_ups_password"
  UPS_ACCOUNT_NUMBER: "your_ups_account"
  DHL_API_KEY: "your_dhl_api_key"
  DHL_ACCOUNT_NUMBER: "your_dhl_account"
  
  # Notification Service Keys
  SENDGRID_API_KEY: "SG.your_sendgrid_api_key"
  TWILIO_ACCOUNT_SID: "your_twilio_account_sid"
  TWILIO_AUTH_TOKEN: "your_twilio_auth_token"
  TWILIO_PHONE_NUMBER: "+1234567890"
  FCM_SERVER_KEY: "your_fcm_server_key"
  SLACK_WEBHOOK_URL: "https://hooks.slack.com/services/your/webhook/url"
  
  # Encryption Keys
  ENCRYPTION_KEY: "your_32_character_encryption_key"
  SIGNING_KEY: "your_signing_key_for_webhooks"
  
  # Monitoring & Observability
  GRAFANA_API_KEY: "your_grafana_api_key"
  DATADOG_API_KEY: "your_datadog_api_key"
  NEW_RELIC_LICENSE_KEY: "your_newrelic_license_key"
  
  # Cloud Provider Credentials
  AWS_ACCESS_KEY_ID: "your_aws_access_key"
  AWS_SECRET_ACCESS_KEY: "your_aws_secret_key"
  AWS_REGION: "us-east-1"
  
---
apiVersion: v1
kind: Secret
metadata:
  name: commerce-secrets-staging
  namespace: commerce-staging
  labels:
    app: commerce-service
    version: v1
    environment: staging
type: Opaque
stringData:
  # Database Credentials
  DB_USERNAME: "commerce_staging_user"
  DB_PASSWORD: "your_staging_db_password_here"
  
  # Redis Password
  REDIS_PASSWORD: "your_staging_redis_password_here"
  
  # JWT Configuration
  JWT_SECRET_KEY: "your_staging_jwt_secret_key_here"
  JWT_ALGORITHM: "HS256"
  JWT_ACCESS_TOKEN_EXPIRE_MINUTES: "60"
  JWT_REFRESH_TOKEN_EXPIRE_DAYS: "30"
  
  # External Service API Keys (Test/Sandbox)
  STRIPE_SECRET_KEY: "sk_test_your_stripe_test_key"
  STRIPE_WEBHOOK_SECRET: "whsec_your_stripe_test_webhook_secret"
  PAYPAL_CLIENT_ID: "your_paypal_sandbox_client_id"
  PAYPAL_CLIENT_SECRET: "your_paypal_sandbox_client_secret"
  
  # Shipping Service Keys (Test)
  FEDEX_API_KEY: "your_fedex_test_api_key"
  FEDEX_ACCOUNT_NUMBER: "your_fedex_test_account"
  FEDEX_METER_NUMBER: "your_fedex_test_meter"
  UPS_API_KEY: "your_ups_test_api_key"
  UPS_USERNAME: "your_ups_test_username"
  UPS_PASSWORD: "your_ups_test_password"
  UPS_ACCOUNT_NUMBER: "your_ups_test_account"
  DHL_API_KEY: "your_dhl_test_api_key"
  DHL_ACCOUNT_NUMBER: "your_dhl_test_account"
  
  # Notification Service Keys (Test)
  SENDGRID_API_KEY: "SG.your_sendgrid_test_api_key"
  TWILIO_ACCOUNT_SID: "your_twilio_test_account_sid"
  TWILIO_AUTH_TOKEN: "your_twilio_test_auth_token"
  TWILIO_PHONE_NUMBER: "+1234567890"
  FCM_SERVER_KEY: "your_fcm_test_server_key"
  SLACK_WEBHOOK_URL: "https://hooks.slack.com/services/your/test/webhook/url"
  
  # Encryption Keys
  ENCRYPTION_KEY: "your_32_char_staging_encryption_key"
  SIGNING_KEY: "your_staging_signing_key_for_webhooks"
  
  # Monitoring & Observability
  GRAFANA_API_KEY: "your_grafana_staging_api_key"
  DATADOG_API_KEY: "your_datadog_staging_api_key"
  NEW_RELIC_LICENSE_KEY: "your_newrelic_staging_license_key"
  
  # Cloud Provider Credentials
  AWS_ACCESS_KEY_ID: "your_aws_staging_access_key"
  AWS_SECRET_ACCESS_KEY: "your_aws_staging_secret_key"
  AWS_REGION: "us-west-2"
