# UPI PSP Service Configuration
service_name: "upi-psp-service"
environment: "development"
port: 8097
log_level: "info"

# Database Configuration
database_url: "postgresql://upi_psp:upi_psp_password@localhost:5432/upi_psp_db?sslmode=disable"

# Redis Configuration
redis:
  host: "localhost"
  port: 6379
  password: ""
  db: 0

# Security Configuration
security:
  jwt_secret: "development-jwt-secret-change-in-production"
  jwt_expiration_hours: 24
  encryption_key: "development-encryption-key-32-bytes"
  bcrypt_cost: 12

# UPI Configuration
upi:
  acquirer_id: "SUUUPRA"
  psp_id: "SUUUPRAPSP"
  merchant_id: "SUUUPRA001"

# External Services
upi_core_service_url: "localhost:50051"
payment_service_url: "http://localhost:8084"
notification_service_url: "http://localhost:8085"

# Observability
prometheus_metrics_port: 9090
jaeger_endpoint: "http://localhost:14268"
