app:
  name: "upi-core"
  version: "1.0.0"
  environment: "development"

server:
  host: "0.0.0.0"
  port: 50051
  read_timeout: "30s"
  write_timeout: "30s"
  idle_timeout: "120s"

database:
  host: "localhost"
  port: 5432
  username: "postgres"
  password: "password"
  database: "upi_core_dev"
  ssl_mode: "disable"
  max_open_conns: 25
  max_idle_conns: 5
  conn_timeout: "10s"

redis:
  host: "localhost"
  port: 6379
  password: ""
  db: 0
  pool_size: 10

kafka:
  brokers: ["localhost:9092"]
  group_id: "upi-core-dev"
  topics:
    transactions: "upi.transactions.dev"
    settlements: "upi.settlements.dev"
    events: "upi.events.dev"

security:
  private_key_path: ""
  public_key_path: ""
  enable_tls: false
  tls_cert_file: ""
  tls_key_file: ""

logging:
  level: "info"
  format: "text"

telemetry:
  enabled: false
  service_name: "upi-core"
  jaeger_endpoint: "http://localhost:14268/api/traces"
  metrics_port: 9090
  sample_rate: 0.1
