apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
- name: elasticsearch
  repo: https://helm.elastic.co
  version: 8.5.1
  releaseName: elasticsearch
  namespace: llm-tutor
  valuesInline:
    replicas: 1
