global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  # Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # Bank Simulator metrics
  - job_name: 'bank-simulator'
    static_configs:
      - targets: ['bank-simulator:9090']
    scrape_interval: 10s
    metrics_path: /metrics
    scheme: http

  # UPI Core metrics
  - job_name: 'upi-core'
    static_configs:
      - targets: ['upi-core:9090']
    scrape_interval: 10s
    metrics_path: /metrics
    scheme: http

  # Node exporter for system metrics (if added)
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']
    scrape_interval: 30s

  # PostgreSQL metrics (if pg_exporter is added)
  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres-exporter:9187']
    scrape_interval: 30s

  # Redis metrics (if redis_exporter is added)
  - job_name: 'redis'
    static_configs:
      - targets: ['redis-exporter:9121']
    scrape_interval: 30s

  # Kafka metrics (if kafka_exporter is added)
  - job_name: 'kafka'
    static_configs:
      - targets: ['kafka-exporter:9308']
    scrape_interval: 30s
