openapi: 3.0.3
info:
  title: Suuupra Identity Service API
  description: |
    Comprehensive user authentication, authorization, and profile management service for the Suuupra platform.
    
    ## Features
    - JWT-based authentication with refresh tokens
    - Role-based access control (RBAC)
    - User profile management
    - Administrative user operations
    - Security features and rate limiting
  version: 1.0.0

servers:
  - url: http://localhost:8080/api/v1
    description: Development server
  - url: https://identity.suuupra.com/api/v1
    description: Production server

paths:
  /auth/register:
    post:
      tags: [Authentication]
      summary: Register new user
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required: [email, password, firstName, lastName]
              properties:
                email:
                  type: string
                  format: email
                password:
                  type: string
                  minLength: 8
                firstName:
                  type: string
                lastName:
                  type: string
                phoneNumber:
                  type: string
      responses:
        '201':
          description: User registered successfully
        '400':
          description: Invalid request data
        '409':
          description: User already exists

  /auth/login:
    post:
      tags: [Authentication]
      summary: User login
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required: [email, password]
              properties:
                email:
                  type: string
                password:
                  type: string
      responses:
        '200':
          description: Login successful
        '401':
          description: Invalid credentials

  /auth/validate:
    post:
      tags: [Authentication]
      summary: Validate JWT token
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Token is valid
        '401':
          description: Token is invalid

  /users/profile:
    get:
      tags: [User Management]
      summary: Get user profile
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Profile retrieved successfully
        '401':
          description: Unauthorized

    put:
      tags: [User Management]
      summary: Update user profile
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                firstName:
                  type: string
                lastName:
                  type: string
                phoneNumber:
                  type: string
      responses:
        '200':
          description: Profile updated successfully

  /users:
    get:
      tags: [User Management]
      summary: List users (admin only)
      security:
        - bearerAuth: []
      parameters:
        - name: page
          in: query
          schema:
            type: integer
            default: 0
        - name: size
          in: query
          schema:
            type: integer
            default: 20
      responses:
        '200':
          description: Users retrieved successfully
        '403':
          description: Admin access required

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

tags:
  - name: Authentication
    description: User authentication operations
  - name: User Management
    description: User profile operations