version: '4'

services:
  # search-crawler Service - Production Ready
  search-crawler:
    build:
      context: .
      dockerfile: Dockerfile
      target: production
    container_name: suuupra-search-crawler
    restart: unless-stopped
    ports:
      - "8094:8094"   # Main service port (aligned with main compose)
      - "9105:9105"   # Metrics port (aligned with main compose)
    environment:
      # Core configuration (aligned with main docker-compose.yml)
      NODE_ENV: production
      PORT: 8094
      METRICS_PORT: 9105
      
      # Database - Using main infrastructure PostgreSQL
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres123}
      POSTGRES_DATABASE: search_crawler
      
      # Redis - Using main infrastructure
      REDIS_HOST: redis
      REDIS_PORT: 6379
      
      # Event streaming - Using main infrastructure Kafka
      KAFKA_BROKERS: kafka:29092
      KAFKA_CLIENT_ID: search-crawler-service
      KAFKA_GROUP_ID: search-crawler-consumers
      
      # Security & Vault - Using main infrastructure
      VAULT_ADDR: http://vault:8200
      VAULT_TOKEN: ${VAULT_TOKEN:-myroot}
      VAULT_MOUNT_PATH: search-crawler
      
      # Observability - Using main infrastructure
      OTEL_SERVICE_NAME: search-crawler-service
      OTEL_SERVICE_VERSION: 1.0.0
      OTEL_EXPORTER_OTLP_ENDPOINT: http://otel-collector:4317
      OTEL_RESOURCE_ATTRIBUTES: service.namespace=suuupra,deployment.environment=docker-compose
      
    volumes:
      - app_logs:/app/logs
    
    # Use main infrastructure services (no separate dependencies)
    external_links:
      - postgres:postgres
      - redis:redis
      - kafka:kafka
      - vault:vault
      - otel-collector:otel-collector
    
    networks:
      - suuupra-network
    
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8094/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 60s
    
    labels:
      - "prometheus.scrape=true"
      - "prometheus.port=9105"

# ===================================================================
# VOLUMES - Aligned with main infrastructure
# ===================================================================
volumes:
  app_logs:
    external: true
    name: suuupra_app_logs

# ===================================================================
# NETWORKS - Using main infrastructure network
# ===================================================================
networks:
  suuupra-network:
    external: true
    name: suuupra-network

# ===================================================================
# NOTES:
# - All infrastructure services (PostgreSQL, Redis, Kafka, Vault, 
#   Prometheus, Grafana, Jaeger) are provided by main infrastructure
# - Use: docker-compose -f ../../docker-compose.infrastructure.yml up -d
# - Then: docker-compose -f docker-compose.yml up -d
# ===================================================================
