groups:
  - name: gateway.rules
    rules:
      - alert: HighGatewayErrorRate
        expr: sum(rate(http_server_errors_total[5m])) / sum(rate(http_requests_total[5m])) > 0.05
        for: 5m
        labels:
          severity: page
        annotations:
          summary: "High 5xx rate detected on API Gateway"
          description: "5xx error rate > 5% over 5 minutes. Investigate upstream health/circuit breakers."

  - name: identity.rules
    rules:
      - alert: ErrorBudgetBurnFast
        expr: (sum(rate(http_server_requests_seconds_count{status=~"5.."}[5m])) / sum(rate(http_server_requests_seconds_count[5m]))) > 0.02
        for: 5m
        labels: { severity: critical }
        annotations:
          summary: Fast burn on error budget (>2% 5xx over 5m)
          description: Investigate token/userinfo endpoints and dependencies

      - alert: ErrorBudgetBurnSlow
        expr: (sum(rate(http_server_requests_seconds_count{status=~"5.."}[1h])) / sum(rate(http_server_requests_seconds_count[1h]))) > 0.005
        for: 1h
        labels: { severity: warning }
        annotations:
          summary: Slow burn on error budget (>0.5% 5xx over 1h)
          description: Sustained errors; check recent deploys and upstreams
      - alert: JWKSFailures
        expr: sum(rate(http_server_requests_seconds_count{uri="/.well-known/jwks.json",status=~"5.."}[5m])) > 0
        for: 2m
        labels:
          severity: warning
        annotations:
          summary: JWKS endpoint failing
          description: High rate of 5xx on JWKS endpoint

      - alert: AuthHighLatencyP95
        expr: histogram_quantile(0.95, sum by (le) (rate(http_server_requests_seconds_bucket{uri=~"/oauth2/token|/api/v1/auth/.*"}[5m]))) > 0.2
        for: 10m
        labels:
          severity: critical
        annotations:
          summary: High p95 auth latency
          description: p95 latency above 200ms for 10m

      - alert: AuthzDeniedSpike
        expr: increase(authz_denied_total[10m]) > 100
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: Authorization denied spike
          description: Denied decisions spiking

      - alert: PolicyEvalLatencyHigh
        expr: histogram_quantile(0.95, sum by (le) (rate(policy_eval_latency_ms_bucket[5m]))) > 50
        for: 10m
        labels:
          severity: warning
        annotations:
          summary: High policy evaluation latency
          description: p95 policy evaluation exceeds 50ms

      - alert: RateLimitSpike
        expr: sum(rate(http_server_requests_seconds_count{status="429"}[5m])) > 10
        for: 5m
        labels:
          severity: info
        annotations:
          summary: Rate limiting spike
          description: Elevated 429 responses detected

      - alert: DPoPReplayDetected
        expr: increase(dpop_replay_errors_total[10m]) > 0
        for: 1m
        labels:
          severity: warning
        annotations:
          summary: DPoP replay attempts detected
          description: At least one DPoP replay error counted in the last 10 minutes

      - alert: DPoPCnfMismatch
        expr: increase(dpop_cnf_mismatch_total[10m]) > 5
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: DPoP cnf.jkt mismatches
          description: Multiple mismatches between access token cnf and DPoP key

      - alert: TokenLatencyHigh
        expr: histogram_quantile(0.95, sum by (le) (rate(http_server_requests_seconds_bucket{uri="/oauth2/token"}[5m]))) > 0.5
        for: 10m
        labels:
          severity: warning
        annotations:
          summary: Token endpoint latency high
          description: P95 latency on /oauth2/token exceeded 500ms

      - alert: WebAuthnFailuresSpike
        expr: (sum(increase(webauthn_register_failure_total[10m])) + sum(increase(webauthn_assert_failure_total[10m]))) > 50
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: WebAuthn failures spiking
          description: High rate of WebAuthn registration/assertion failures detected

      - alert: MTLSHandshakeFailures
        expr: sum(rate(server_tls_handshake_failures_total[5m])) > 1
        for: 10m
        labels:
          severity: warning
        annotations:
          summary: Elevated TLS handshake failures
          description: Possible client cert/mTLS issues affecting identity traffic

