version: '3.8'

services:
  content-delivery:
    build: .
    ports:
      - "3004:3004"
    environment:
      - NODE_ENV=development
      - PORT=3004
      - CDN_BUCKET=suuupra-cdn-dev
      - CACHE_TTL=3600
    volumes:
      - ./src:/app/src
      - ./uploads:/app/uploads
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3004/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - suuupra-network

  redis-cache:
    image: redis:7-alpine
    ports:
      - "6381:6379"
    command: redis-server --appendonly yes
    volumes:
      - redis_cache_data:/data
    networks:
      - suuupra-network

volumes:
  redis_cache_data:

networks:
  suuupra-network:
    driver: bridge