image:
  repository: ghcr.io/your-org/content-service
  tag: latest
  pullPolicy: IfNotPresent

canary:
  enabled: false
  weight: 0 # Percentage of traffic to send to canary (0-100)

deployment:
  strategy: rollingUpdate # Options: rollingUpdate, recreate, canary

service:
  replicas: 1 # Default number of replicas

  port: 8082
  metricsPort: 9090
  type: ClusterIP

env:
  NODE_ENV: production
  ENABLE_BACKGROUND_JOBS: "false"
  LOG_LEVEL: info

resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 200m
    memory: 256Mi

livenessProbe:
  path: /health
  initialDelaySeconds: 20
  periodSeconds: 10

readinessProbe:
  path: /health
  initialDelaySeconds: 10
  periodSeconds: 5

nodeSelector: {}
tolerations: []
affinity: {}

