apiVersion: apps/v1
kind: Deployment
metadata:
  name: vllm
  namespace: llm-tutor
  labels:
    app: vllm
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vllm
  template:
    metadata:
      labels:
        app: vllm
    spec:
      containers:
      - name: vllm
        image: vllm/vllm-openai:latest
        args:
        - --model
        - /mnt/models/mistral-7b-instruct-v0.2
        ports:
        - containerPort: 8000
        resources:
          limits:
            nvidia.com/gpu: 1
