global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  # Payment Gateway Service
  - job_name: 'payments-service'
    static_configs:
      - targets: ['payments:9090']
    scrape_interval: 10s
    metrics_path: /metrics
    honor_labels: true

  # UPI Core Service 
  - job_name: 'upi-core-service'
    static_configs:
      - targets: ['upi-core:9090']
    scrape_interval: 10s
    metrics_path: /metrics
    honor_labels: true

  # Bank Simulator Service
  - job_name: 'bank-simulator-service'
    static_configs:
      - targets: ['bank-simulator:9094']
    scrape_interval: 10s
    metrics_path: /metrics
    honor_labels: true

  # PostgreSQL Database
  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres:5432']
    scrape_interval: 30s

  # Redis Cache
  - job_name: 'redis'
    static_configs:
      - targets: ['redis:6379']
    scrape_interval: 30s

  # Node Exporter (if available)
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']
    scrape_interval: 30s

  # Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']