apiVersion: apps/v1
kind: Deployment
metadata:
  name: content-delivery
  labels:
    app: content-delivery
spec:
  replicas: 3
  selector:
    matchLabels:
      app: content-delivery
  template:
    metadata:
      labels:
        app: content-delivery
    spec:
      containers:
      - name: content-delivery
        image: suuupra/content-delivery:latest
        ports:
        - containerPort: 3004
        env:
        - name: NODE_ENV
          value: "production"
        - name: PORT
          value: "3004"
        - name: CDN_BUCKET
          valueFrom:
            secretKeyRef:
              name: content-delivery-secrets
              key: cdn-bucket
        livenessProbe:
          httpGet:
            path: /health
            port: 3004
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 3004
          initialDelaySeconds: 5
          periodSeconds: 5
        resources:
          limits:
            cpu: 500m
            memory: 512Mi
          requests:
            cpu: 250m
            memory: 256Mi