apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: mass-live-base

resources:
  - deployment.yaml
  - service.yaml
  - ingress.yaml
  - hpa.yaml
  - pdb.yaml
  - network-policy.yaml
  - service-monitor.yaml

commonLabels:
  app: mass-live
  service: mass-live
  component: streaming

namespace: suuupra

images:
  - name: suuupra/mass-live
    newTag: latest

configMapGenerator:
  - name: mass-live-config
    literals:
      - s3-bucket=suuupra-mass-live
      - aws-region=us-east-1
      - cdn-base-url=https://cdn.suuupra.com/mass-live
      - cdn-provider=cloudflare
      - log-level=info
      - llhls-enabled=true
      - max-concurrent-streams=1000
      - max-viewers-per-stream=50000
      - jaeger-endpoint=http://jaeger-collector:14268/api/traces

secretGenerator:
  - name: mass-live-secrets
    literals:
      - database-url=postgres://user:password@postgres:5432/mass_live_db?sslmode=disable
      - redis-url=redis://redis:6379/5
      - jwt-secret=your-super-secret-jwt-key-change-in-production
      - aws-access-key-id=your-aws-access-key-id
      - aws-secret-access-key=your-aws-secret-access-key
    type: Opaque

replicas:
  - name: mass-live-deployment
    count: 3

patchesStrategicMerge:
  - patches/resource-limits.yaml

patchesJson6902:
  - target:
      group: apps
      version: v1
      kind: Deployment
      name: mass-live-deployment
    path: patches/add-annotations.yaml
