// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.7
// 	protoc        v6.32.0
// source: proto/upi_core.proto

package upi_core

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Enums
type TransactionType int32

const (
	TransactionType_TRANSACTION_TYPE_UNSPECIFIED TransactionType = 0
	TransactionType_TRANSACTION_TYPE_P2P         TransactionType = 1
	TransactionType_TRANSACTION_TYPE_P2M         TransactionType = 2
	TransactionType_TRANSACTION_TYPE_M2P         TransactionType = 3
	TransactionType_TRANSACTION_TYPE_REFUND      TransactionType = 4
)

// Enum value maps for TransactionType.
var (
	TransactionType_name = map[int32]string{
		0: "TRANSACTION_TYPE_UNSPECIFIED",
		1: "TRANSACTION_TYPE_P2P",
		2: "TRANSACTION_TYPE_P2M",
		3: "TRANSACTION_TYPE_M2P",
		4: "TRANSACTION_TYPE_REFUND",
	}
	TransactionType_value = map[string]int32{
		"TRANSACTION_TYPE_UNSPECIFIED": 0,
		"TRANSACTION_TYPE_P2P":         1,
		"TRANSACTION_TYPE_P2M":         2,
		"TRANSACTION_TYPE_M2P":         3,
		"TRANSACTION_TYPE_REFUND":      4,
	}
)

func (x TransactionType) Enum() *TransactionType {
	p := new(TransactionType)
	*p = x
	return p
}

func (x TransactionType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TransactionType) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_upi_core_proto_enumTypes[0].Descriptor()
}

func (TransactionType) Type() protoreflect.EnumType {
	return &file_proto_upi_core_proto_enumTypes[0]
}

func (x TransactionType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TransactionType.Descriptor instead.
func (TransactionType) EnumDescriptor() ([]byte, []int) {
	return file_proto_upi_core_proto_rawDescGZIP(), []int{0}
}

type TransactionStatus int32

const (
	TransactionStatus_TRANSACTION_STATUS_UNSPECIFIED TransactionStatus = 0
	TransactionStatus_TRANSACTION_STATUS_PENDING     TransactionStatus = 1
	TransactionStatus_TRANSACTION_STATUS_SUCCESS     TransactionStatus = 2
	TransactionStatus_TRANSACTION_STATUS_FAILED      TransactionStatus = 3
	TransactionStatus_TRANSACTION_STATUS_TIMEOUT     TransactionStatus = 4
	TransactionStatus_TRANSACTION_STATUS_CANCELLED   TransactionStatus = 5
	TransactionStatus_TRANSACTION_STATUS_REVERSED    TransactionStatus = 6
)

// Enum value maps for TransactionStatus.
var (
	TransactionStatus_name = map[int32]string{
		0: "TRANSACTION_STATUS_UNSPECIFIED",
		1: "TRANSACTION_STATUS_PENDING",
		2: "TRANSACTION_STATUS_SUCCESS",
		3: "TRANSACTION_STATUS_FAILED",
		4: "TRANSACTION_STATUS_TIMEOUT",
		5: "TRANSACTION_STATUS_CANCELLED",
		6: "TRANSACTION_STATUS_REVERSED",
	}
	TransactionStatus_value = map[string]int32{
		"TRANSACTION_STATUS_UNSPECIFIED": 0,
		"TRANSACTION_STATUS_PENDING":     1,
		"TRANSACTION_STATUS_SUCCESS":     2,
		"TRANSACTION_STATUS_FAILED":      3,
		"TRANSACTION_STATUS_TIMEOUT":     4,
		"TRANSACTION_STATUS_CANCELLED":   5,
		"TRANSACTION_STATUS_REVERSED":    6,
	}
)

func (x TransactionStatus) Enum() *TransactionStatus {
	p := new(TransactionStatus)
	*p = x
	return p
}

func (x TransactionStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TransactionStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_upi_core_proto_enumTypes[1].Descriptor()
}

func (TransactionStatus) Type() protoreflect.EnumType {
	return &file_proto_upi_core_proto_enumTypes[1]
}

func (x TransactionStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TransactionStatus.Descriptor instead.
func (TransactionStatus) EnumDescriptor() ([]byte, []int) {
	return file_proto_upi_core_proto_rawDescGZIP(), []int{1}
}

// Transaction Processing Messages
type TransactionRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	TransactionId    string                 `protobuf:"bytes,1,opt,name=transaction_id,json=transactionId,proto3" json:"transaction_id,omitempty"`
	PayerVpa         string                 `protobuf:"bytes,2,opt,name=payer_vpa,json=payerVpa,proto3" json:"payer_vpa,omitempty"`
	PayeeVpa         string                 `protobuf:"bytes,3,opt,name=payee_vpa,json=payeeVpa,proto3" json:"payee_vpa,omitempty"`
	AmountPaisa      int64                  `protobuf:"varint,4,opt,name=amount_paisa,json=amountPaisa,proto3" json:"amount_paisa,omitempty"`
	Type             TransactionType        `protobuf:"varint,5,opt,name=type,proto3,enum=upi.core.TransactionType" json:"type,omitempty"`
	Reference        string                 `protobuf:"bytes,6,opt,name=reference,proto3" json:"reference,omitempty"`
	PayerBankCode    string                 `protobuf:"bytes,7,opt,name=payer_bank_code,json=payerBankCode,proto3" json:"payer_bank_code,omitempty"`
	PayeeBankCode    string                 `protobuf:"bytes,8,opt,name=payee_bank_code,json=payeeBankCode,proto3" json:"payee_bank_code,omitempty"`
	DigitalSignature string                 `protobuf:"bytes,9,opt,name=digital_signature,json=digitalSignature,proto3" json:"digital_signature,omitempty"`
	InitiatedAt      *timestamppb.Timestamp `protobuf:"bytes,10,opt,name=initiated_at,json=initiatedAt,proto3" json:"initiated_at,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *TransactionRequest) Reset() {
	*x = TransactionRequest{}
	mi := &file_proto_upi_core_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransactionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransactionRequest) ProtoMessage() {}

func (x *TransactionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_upi_core_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransactionRequest.ProtoReflect.Descriptor instead.
func (*TransactionRequest) Descriptor() ([]byte, []int) {
	return file_proto_upi_core_proto_rawDescGZIP(), []int{0}
}

func (x *TransactionRequest) GetTransactionId() string {
	if x != nil {
		return x.TransactionId
	}
	return ""
}

func (x *TransactionRequest) GetPayerVpa() string {
	if x != nil {
		return x.PayerVpa
	}
	return ""
}

func (x *TransactionRequest) GetPayeeVpa() string {
	if x != nil {
		return x.PayeeVpa
	}
	return ""
}

func (x *TransactionRequest) GetAmountPaisa() int64 {
	if x != nil {
		return x.AmountPaisa
	}
	return 0
}

func (x *TransactionRequest) GetType() TransactionType {
	if x != nil {
		return x.Type
	}
	return TransactionType_TRANSACTION_TYPE_UNSPECIFIED
}

func (x *TransactionRequest) GetReference() string {
	if x != nil {
		return x.Reference
	}
	return ""
}

func (x *TransactionRequest) GetPayerBankCode() string {
	if x != nil {
		return x.PayerBankCode
	}
	return ""
}

func (x *TransactionRequest) GetPayeeBankCode() string {
	if x != nil {
		return x.PayeeBankCode
	}
	return ""
}

func (x *TransactionRequest) GetDigitalSignature() string {
	if x != nil {
		return x.DigitalSignature
	}
	return ""
}

func (x *TransactionRequest) GetInitiatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.InitiatedAt
	}
	return nil
}

type TransactionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TransactionId string                 `protobuf:"bytes,1,opt,name=transaction_id,json=transactionId,proto3" json:"transaction_id,omitempty"`
	Rrn           string                 `protobuf:"bytes,2,opt,name=rrn,proto3" json:"rrn,omitempty"`
	Status        TransactionStatus      `protobuf:"varint,3,opt,name=status,proto3,enum=upi.core.TransactionStatus" json:"status,omitempty"`
	PayerBankCode string                 `protobuf:"bytes,4,opt,name=payer_bank_code,json=payerBankCode,proto3" json:"payer_bank_code,omitempty"`
	PayeeBankCode string                 `protobuf:"bytes,5,opt,name=payee_bank_code,json=payeeBankCode,proto3" json:"payee_bank_code,omitempty"`
	Fees          *TransactionFees       `protobuf:"bytes,6,opt,name=fees,proto3" json:"fees,omitempty"`
	SettlementId  string                 `protobuf:"bytes,7,opt,name=settlement_id,json=settlementId,proto3" json:"settlement_id,omitempty"`
	ErrorCode     string                 `protobuf:"bytes,8,opt,name=error_code,json=errorCode,proto3" json:"error_code,omitempty"`
	ErrorMessage  string                 `protobuf:"bytes,9,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	ProcessedAt   *timestamppb.Timestamp `protobuf:"bytes,10,opt,name=processed_at,json=processedAt,proto3" json:"processed_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TransactionResponse) Reset() {
	*x = TransactionResponse{}
	mi := &file_proto_upi_core_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransactionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransactionResponse) ProtoMessage() {}

func (x *TransactionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_upi_core_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransactionResponse.ProtoReflect.Descriptor instead.
func (*TransactionResponse) Descriptor() ([]byte, []int) {
	return file_proto_upi_core_proto_rawDescGZIP(), []int{1}
}

func (x *TransactionResponse) GetTransactionId() string {
	if x != nil {
		return x.TransactionId
	}
	return ""
}

func (x *TransactionResponse) GetRrn() string {
	if x != nil {
		return x.Rrn
	}
	return ""
}

func (x *TransactionResponse) GetStatus() TransactionStatus {
	if x != nil {
		return x.Status
	}
	return TransactionStatus_TRANSACTION_STATUS_UNSPECIFIED
}

func (x *TransactionResponse) GetPayerBankCode() string {
	if x != nil {
		return x.PayerBankCode
	}
	return ""
}

func (x *TransactionResponse) GetPayeeBankCode() string {
	if x != nil {
		return x.PayeeBankCode
	}
	return ""
}

func (x *TransactionResponse) GetFees() *TransactionFees {
	if x != nil {
		return x.Fees
	}
	return nil
}

func (x *TransactionResponse) GetSettlementId() string {
	if x != nil {
		return x.SettlementId
	}
	return ""
}

func (x *TransactionResponse) GetErrorCode() string {
	if x != nil {
		return x.ErrorCode
	}
	return ""
}

func (x *TransactionResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

func (x *TransactionResponse) GetProcessedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ProcessedAt
	}
	return nil
}

type TransactionFees struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	ProcessingFeePaisa int64                  `protobuf:"varint,1,opt,name=processing_fee_paisa,json=processingFeePaisa,proto3" json:"processing_fee_paisa,omitempty"`
	GstPaisa           int64                  `protobuf:"varint,2,opt,name=gst_paisa,json=gstPaisa,proto3" json:"gst_paisa,omitempty"`
	TotalFeePaisa      int64                  `protobuf:"varint,3,opt,name=total_fee_paisa,json=totalFeePaisa,proto3" json:"total_fee_paisa,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *TransactionFees) Reset() {
	*x = TransactionFees{}
	mi := &file_proto_upi_core_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransactionFees) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransactionFees) ProtoMessage() {}

func (x *TransactionFees) ProtoReflect() protoreflect.Message {
	mi := &file_proto_upi_core_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransactionFees.ProtoReflect.Descriptor instead.
func (*TransactionFees) Descriptor() ([]byte, []int) {
	return file_proto_upi_core_proto_rawDescGZIP(), []int{2}
}

func (x *TransactionFees) GetProcessingFeePaisa() int64 {
	if x != nil {
		return x.ProcessingFeePaisa
	}
	return 0
}

func (x *TransactionFees) GetGstPaisa() int64 {
	if x != nil {
		return x.GstPaisa
	}
	return 0
}

func (x *TransactionFees) GetTotalFeePaisa() int64 {
	if x != nil {
		return x.TotalFeePaisa
	}
	return 0
}

type TransactionStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TransactionId string                 `protobuf:"bytes,1,opt,name=transaction_id,json=transactionId,proto3" json:"transaction_id,omitempty"`
	BankCode      string                 `protobuf:"bytes,2,opt,name=bank_code,json=bankCode,proto3" json:"bank_code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TransactionStatusRequest) Reset() {
	*x = TransactionStatusRequest{}
	mi := &file_proto_upi_core_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransactionStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransactionStatusRequest) ProtoMessage() {}

func (x *TransactionStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_upi_core_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransactionStatusRequest.ProtoReflect.Descriptor instead.
func (*TransactionStatusRequest) Descriptor() ([]byte, []int) {
	return file_proto_upi_core_proto_rawDescGZIP(), []int{3}
}

func (x *TransactionStatusRequest) GetTransactionId() string {
	if x != nil {
		return x.TransactionId
	}
	return ""
}

func (x *TransactionStatusRequest) GetBankCode() string {
	if x != nil {
		return x.BankCode
	}
	return ""
}

type TransactionStatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TransactionId string                 `protobuf:"bytes,1,opt,name=transaction_id,json=transactionId,proto3" json:"transaction_id,omitempty"`
	Rrn           string                 `protobuf:"bytes,2,opt,name=rrn,proto3" json:"rrn,omitempty"`
	Status        TransactionStatus      `protobuf:"varint,3,opt,name=status,proto3,enum=upi.core.TransactionStatus" json:"status,omitempty"`
	Events        []*TransactionEvent    `protobuf:"bytes,4,rep,name=events,proto3" json:"events,omitempty"`
	AmountPaisa   int64                  `protobuf:"varint,5,opt,name=amount_paisa,json=amountPaisa,proto3" json:"amount_paisa,omitempty"`
	PayerVpa      string                 `protobuf:"bytes,6,opt,name=payer_vpa,json=payerVpa,proto3" json:"payer_vpa,omitempty"`
	PayeeVpa      string                 `protobuf:"bytes,7,opt,name=payee_vpa,json=payeeVpa,proto3" json:"payee_vpa,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TransactionStatusResponse) Reset() {
	*x = TransactionStatusResponse{}
	mi := &file_proto_upi_core_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransactionStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransactionStatusResponse) ProtoMessage() {}

func (x *TransactionStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_upi_core_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransactionStatusResponse.ProtoReflect.Descriptor instead.
func (*TransactionStatusResponse) Descriptor() ([]byte, []int) {
	return file_proto_upi_core_proto_rawDescGZIP(), []int{4}
}

func (x *TransactionStatusResponse) GetTransactionId() string {
	if x != nil {
		return x.TransactionId
	}
	return ""
}

func (x *TransactionStatusResponse) GetRrn() string {
	if x != nil {
		return x.Rrn
	}
	return ""
}

func (x *TransactionStatusResponse) GetStatus() TransactionStatus {
	if x != nil {
		return x.Status
	}
	return TransactionStatus_TRANSACTION_STATUS_UNSPECIFIED
}

func (x *TransactionStatusResponse) GetEvents() []*TransactionEvent {
	if x != nil {
		return x.Events
	}
	return nil
}

func (x *TransactionStatusResponse) GetAmountPaisa() int64 {
	if x != nil {
		return x.AmountPaisa
	}
	return 0
}

func (x *TransactionStatusResponse) GetPayerVpa() string {
	if x != nil {
		return x.PayerVpa
	}
	return ""
}

func (x *TransactionStatusResponse) GetPayeeVpa() string {
	if x != nil {
		return x.PayeeVpa
	}
	return ""
}

func (x *TransactionStatusResponse) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *TransactionStatusResponse) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type TransactionEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Status        TransactionStatus      `protobuf:"varint,2,opt,name=status,proto3,enum=upi.core.TransactionStatus" json:"status,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TransactionEvent) Reset() {
	*x = TransactionEvent{}
	mi := &file_proto_upi_core_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransactionEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransactionEvent) ProtoMessage() {}

func (x *TransactionEvent) ProtoReflect() protoreflect.Message {
	mi := &file_proto_upi_core_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransactionEvent.ProtoReflect.Descriptor instead.
func (*TransactionEvent) Descriptor() ([]byte, []int) {
	return file_proto_upi_core_proto_rawDescGZIP(), []int{5}
}

func (x *TransactionEvent) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *TransactionEvent) GetStatus() TransactionStatus {
	if x != nil {
		return x.Status
	}
	return TransactionStatus_TRANSACTION_STATUS_UNSPECIFIED
}

func (x *TransactionEvent) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

type CancelTransactionRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	TransactionId    string                 `protobuf:"bytes,1,opt,name=transaction_id,json=transactionId,proto3" json:"transaction_id,omitempty"`
	BankCode         string                 `protobuf:"bytes,2,opt,name=bank_code,json=bankCode,proto3" json:"bank_code,omitempty"`
	Reason           string                 `protobuf:"bytes,3,opt,name=reason,proto3" json:"reason,omitempty"`
	DigitalSignature string                 `protobuf:"bytes,4,opt,name=digital_signature,json=digitalSignature,proto3" json:"digital_signature,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *CancelTransactionRequest) Reset() {
	*x = CancelTransactionRequest{}
	mi := &file_proto_upi_core_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelTransactionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelTransactionRequest) ProtoMessage() {}

func (x *CancelTransactionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_upi_core_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelTransactionRequest.ProtoReflect.Descriptor instead.
func (*CancelTransactionRequest) Descriptor() ([]byte, []int) {
	return file_proto_upi_core_proto_rawDescGZIP(), []int{6}
}

func (x *CancelTransactionRequest) GetTransactionId() string {
	if x != nil {
		return x.TransactionId
	}
	return ""
}

func (x *CancelTransactionRequest) GetBankCode() string {
	if x != nil {
		return x.BankCode
	}
	return ""
}

func (x *CancelTransactionRequest) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *CancelTransactionRequest) GetDigitalSignature() string {
	if x != nil {
		return x.DigitalSignature
	}
	return ""
}

type CancelTransactionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	ErrorCode     string                 `protobuf:"bytes,2,opt,name=error_code,json=errorCode,proto3" json:"error_code,omitempty"`
	ErrorMessage  string                 `protobuf:"bytes,3,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	CancelledAt   *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=cancelled_at,json=cancelledAt,proto3" json:"cancelled_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelTransactionResponse) Reset() {
	*x = CancelTransactionResponse{}
	mi := &file_proto_upi_core_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelTransactionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelTransactionResponse) ProtoMessage() {}

func (x *CancelTransactionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_upi_core_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelTransactionResponse.ProtoReflect.Descriptor instead.
func (*CancelTransactionResponse) Descriptor() ([]byte, []int) {
	return file_proto_upi_core_proto_rawDescGZIP(), []int{7}
}

func (x *CancelTransactionResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *CancelTransactionResponse) GetErrorCode() string {
	if x != nil {
		return x.ErrorCode
	}
	return ""
}

func (x *CancelTransactionResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

func (x *CancelTransactionResponse) GetCancelledAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CancelledAt
	}
	return nil
}

type ReverseTransactionRequest struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	OriginalTransactionId string                 `protobuf:"bytes,1,opt,name=original_transaction_id,json=originalTransactionId,proto3" json:"original_transaction_id,omitempty"`
	ReversalTransactionId string                 `protobuf:"bytes,2,opt,name=reversal_transaction_id,json=reversalTransactionId,proto3" json:"reversal_transaction_id,omitempty"`
	BankCode              string                 `protobuf:"bytes,3,opt,name=bank_code,json=bankCode,proto3" json:"bank_code,omitempty"`
	Reason                string                 `protobuf:"bytes,4,opt,name=reason,proto3" json:"reason,omitempty"`
	DigitalSignature      string                 `protobuf:"bytes,5,opt,name=digital_signature,json=digitalSignature,proto3" json:"digital_signature,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *ReverseTransactionRequest) Reset() {
	*x = ReverseTransactionRequest{}
	mi := &file_proto_upi_core_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReverseTransactionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReverseTransactionRequest) ProtoMessage() {}

func (x *ReverseTransactionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_upi_core_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReverseTransactionRequest.ProtoReflect.Descriptor instead.
func (*ReverseTransactionRequest) Descriptor() ([]byte, []int) {
	return file_proto_upi_core_proto_rawDescGZIP(), []int{8}
}

func (x *ReverseTransactionRequest) GetOriginalTransactionId() string {
	if x != nil {
		return x.OriginalTransactionId
	}
	return ""
}

func (x *ReverseTransactionRequest) GetReversalTransactionId() string {
	if x != nil {
		return x.ReversalTransactionId
	}
	return ""
}

func (x *ReverseTransactionRequest) GetBankCode() string {
	if x != nil {
		return x.BankCode
	}
	return ""
}

func (x *ReverseTransactionRequest) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *ReverseTransactionRequest) GetDigitalSignature() string {
	if x != nil {
		return x.DigitalSignature
	}
	return ""
}

type ReverseTransactionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	ReversalRrn   string                 `protobuf:"bytes,2,opt,name=reversal_rrn,json=reversalRrn,proto3" json:"reversal_rrn,omitempty"`
	ErrorCode     string                 `protobuf:"bytes,3,opt,name=error_code,json=errorCode,proto3" json:"error_code,omitempty"`
	ErrorMessage  string                 `protobuf:"bytes,4,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	ReversedAt    *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=reversed_at,json=reversedAt,proto3" json:"reversed_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReverseTransactionResponse) Reset() {
	*x = ReverseTransactionResponse{}
	mi := &file_proto_upi_core_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReverseTransactionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReverseTransactionResponse) ProtoMessage() {}

func (x *ReverseTransactionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_upi_core_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReverseTransactionResponse.ProtoReflect.Descriptor instead.
func (*ReverseTransactionResponse) Descriptor() ([]byte, []int) {
	return file_proto_upi_core_proto_rawDescGZIP(), []int{9}
}

func (x *ReverseTransactionResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ReverseTransactionResponse) GetReversalRrn() string {
	if x != nil {
		return x.ReversalRrn
	}
	return ""
}

func (x *ReverseTransactionResponse) GetErrorCode() string {
	if x != nil {
		return x.ErrorCode
	}
	return ""
}

func (x *ReverseTransactionResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

func (x *ReverseTransactionResponse) GetReversedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ReversedAt
	}
	return nil
}

// VPA Management Messages
type ResolveVPARequest struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Vpa                string                 `protobuf:"bytes,1,opt,name=vpa,proto3" json:"vpa,omitempty"`
	RequestingBankCode string                 `protobuf:"bytes,2,opt,name=requesting_bank_code,json=requestingBankCode,proto3" json:"requesting_bank_code,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *ResolveVPARequest) Reset() {
	*x = ResolveVPARequest{}
	mi := &file_proto_upi_core_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResolveVPARequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResolveVPARequest) ProtoMessage() {}

func (x *ResolveVPARequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_upi_core_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResolveVPARequest.ProtoReflect.Descriptor instead.
func (*ResolveVPARequest) Descriptor() ([]byte, []int) {
	return file_proto_upi_core_proto_rawDescGZIP(), []int{10}
}

func (x *ResolveVPARequest) GetVpa() string {
	if x != nil {
		return x.Vpa
	}
	return ""
}

func (x *ResolveVPARequest) GetRequestingBankCode() string {
	if x != nil {
		return x.RequestingBankCode
	}
	return ""
}

type ResolveVPAResponse struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Exists            bool                   `protobuf:"varint,1,opt,name=exists,proto3" json:"exists,omitempty"`
	BankCode          string                 `protobuf:"bytes,2,opt,name=bank_code,json=bankCode,proto3" json:"bank_code,omitempty"`
	AccountNumber     string                 `protobuf:"bytes,3,opt,name=account_number,json=accountNumber,proto3" json:"account_number,omitempty"`
	AccountHolderName string                 `protobuf:"bytes,4,opt,name=account_holder_name,json=accountHolderName,proto3" json:"account_holder_name,omitempty"`
	IsActive          bool                   `protobuf:"varint,5,opt,name=is_active,json=isActive,proto3" json:"is_active,omitempty"`
	ErrorCode         string                 `protobuf:"bytes,6,opt,name=error_code,json=errorCode,proto3" json:"error_code,omitempty"`
	ErrorMessage      string                 `protobuf:"bytes,7,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *ResolveVPAResponse) Reset() {
	*x = ResolveVPAResponse{}
	mi := &file_proto_upi_core_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResolveVPAResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResolveVPAResponse) ProtoMessage() {}

func (x *ResolveVPAResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_upi_core_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResolveVPAResponse.ProtoReflect.Descriptor instead.
func (*ResolveVPAResponse) Descriptor() ([]byte, []int) {
	return file_proto_upi_core_proto_rawDescGZIP(), []int{11}
}

func (x *ResolveVPAResponse) GetExists() bool {
	if x != nil {
		return x.Exists
	}
	return false
}

func (x *ResolveVPAResponse) GetBankCode() string {
	if x != nil {
		return x.BankCode
	}
	return ""
}

func (x *ResolveVPAResponse) GetAccountNumber() string {
	if x != nil {
		return x.AccountNumber
	}
	return ""
}

func (x *ResolveVPAResponse) GetAccountHolderName() string {
	if x != nil {
		return x.AccountHolderName
	}
	return ""
}

func (x *ResolveVPAResponse) GetIsActive() bool {
	if x != nil {
		return x.IsActive
	}
	return false
}

func (x *ResolveVPAResponse) GetErrorCode() string {
	if x != nil {
		return x.ErrorCode
	}
	return ""
}

func (x *ResolveVPAResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

type RegisterVPARequest struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Vpa               string                 `protobuf:"bytes,1,opt,name=vpa,proto3" json:"vpa,omitempty"`
	BankCode          string                 `protobuf:"bytes,2,opt,name=bank_code,json=bankCode,proto3" json:"bank_code,omitempty"`
	AccountNumber     string                 `protobuf:"bytes,3,opt,name=account_number,json=accountNumber,proto3" json:"account_number,omitempty"`
	AccountHolderName string                 `protobuf:"bytes,4,opt,name=account_holder_name,json=accountHolderName,proto3" json:"account_holder_name,omitempty"`
	MobileNumber      string                 `protobuf:"bytes,5,opt,name=mobile_number,json=mobileNumber,proto3" json:"mobile_number,omitempty"`
	DigitalSignature  string                 `protobuf:"bytes,6,opt,name=digital_signature,json=digitalSignature,proto3" json:"digital_signature,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *RegisterVPARequest) Reset() {
	*x = RegisterVPARequest{}
	mi := &file_proto_upi_core_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterVPARequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterVPARequest) ProtoMessage() {}

func (x *RegisterVPARequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_upi_core_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterVPARequest.ProtoReflect.Descriptor instead.
func (*RegisterVPARequest) Descriptor() ([]byte, []int) {
	return file_proto_upi_core_proto_rawDescGZIP(), []int{12}
}

func (x *RegisterVPARequest) GetVpa() string {
	if x != nil {
		return x.Vpa
	}
	return ""
}

func (x *RegisterVPARequest) GetBankCode() string {
	if x != nil {
		return x.BankCode
	}
	return ""
}

func (x *RegisterVPARequest) GetAccountNumber() string {
	if x != nil {
		return x.AccountNumber
	}
	return ""
}

func (x *RegisterVPARequest) GetAccountHolderName() string {
	if x != nil {
		return x.AccountHolderName
	}
	return ""
}

func (x *RegisterVPARequest) GetMobileNumber() string {
	if x != nil {
		return x.MobileNumber
	}
	return ""
}

func (x *RegisterVPARequest) GetDigitalSignature() string {
	if x != nil {
		return x.DigitalSignature
	}
	return ""
}

type RegisterVPAResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	VpaId         string                 `protobuf:"bytes,2,opt,name=vpa_id,json=vpaId,proto3" json:"vpa_id,omitempty"`
	ErrorCode     string                 `protobuf:"bytes,3,opt,name=error_code,json=errorCode,proto3" json:"error_code,omitempty"`
	ErrorMessage  string                 `protobuf:"bytes,4,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	RegisteredAt  *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=registered_at,json=registeredAt,proto3" json:"registered_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterVPAResponse) Reset() {
	*x = RegisterVPAResponse{}
	mi := &file_proto_upi_core_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterVPAResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterVPAResponse) ProtoMessage() {}

func (x *RegisterVPAResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_upi_core_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterVPAResponse.ProtoReflect.Descriptor instead.
func (*RegisterVPAResponse) Descriptor() ([]byte, []int) {
	return file_proto_upi_core_proto_rawDescGZIP(), []int{13}
}

func (x *RegisterVPAResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *RegisterVPAResponse) GetVpaId() string {
	if x != nil {
		return x.VpaId
	}
	return ""
}

func (x *RegisterVPAResponse) GetErrorCode() string {
	if x != nil {
		return x.ErrorCode
	}
	return ""
}

func (x *RegisterVPAResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

func (x *RegisterVPAResponse) GetRegisteredAt() *timestamppb.Timestamp {
	if x != nil {
		return x.RegisteredAt
	}
	return nil
}

type UpdateVPARequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Vpa              string                 `protobuf:"bytes,1,opt,name=vpa,proto3" json:"vpa,omitempty"`
	BankCode         string                 `protobuf:"bytes,2,opt,name=bank_code,json=bankCode,proto3" json:"bank_code,omitempty"`
	NewAccountNumber string                 `protobuf:"bytes,3,opt,name=new_account_number,json=newAccountNumber,proto3" json:"new_account_number,omitempty"`
	DigitalSignature string                 `protobuf:"bytes,4,opt,name=digital_signature,json=digitalSignature,proto3" json:"digital_signature,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *UpdateVPARequest) Reset() {
	*x = UpdateVPARequest{}
	mi := &file_proto_upi_core_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateVPARequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateVPARequest) ProtoMessage() {}

func (x *UpdateVPARequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_upi_core_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateVPARequest.ProtoReflect.Descriptor instead.
func (*UpdateVPARequest) Descriptor() ([]byte, []int) {
	return file_proto_upi_core_proto_rawDescGZIP(), []int{14}
}

func (x *UpdateVPARequest) GetVpa() string {
	if x != nil {
		return x.Vpa
	}
	return ""
}

func (x *UpdateVPARequest) GetBankCode() string {
	if x != nil {
		return x.BankCode
	}
	return ""
}

func (x *UpdateVPARequest) GetNewAccountNumber() string {
	if x != nil {
		return x.NewAccountNumber
	}
	return ""
}

func (x *UpdateVPARequest) GetDigitalSignature() string {
	if x != nil {
		return x.DigitalSignature
	}
	return ""
}

type UpdateVPAResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	ErrorCode     string                 `protobuf:"bytes,2,opt,name=error_code,json=errorCode,proto3" json:"error_code,omitempty"`
	ErrorMessage  string                 `protobuf:"bytes,3,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateVPAResponse) Reset() {
	*x = UpdateVPAResponse{}
	mi := &file_proto_upi_core_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateVPAResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateVPAResponse) ProtoMessage() {}

func (x *UpdateVPAResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_upi_core_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateVPAResponse.ProtoReflect.Descriptor instead.
func (*UpdateVPAResponse) Descriptor() ([]byte, []int) {
	return file_proto_upi_core_proto_rawDescGZIP(), []int{15}
}

func (x *UpdateVPAResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *UpdateVPAResponse) GetErrorCode() string {
	if x != nil {
		return x.ErrorCode
	}
	return ""
}

func (x *UpdateVPAResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

func (x *UpdateVPAResponse) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type DeactivateVPARequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Vpa              string                 `protobuf:"bytes,1,opt,name=vpa,proto3" json:"vpa,omitempty"`
	BankCode         string                 `protobuf:"bytes,2,opt,name=bank_code,json=bankCode,proto3" json:"bank_code,omitempty"`
	DigitalSignature string                 `protobuf:"bytes,3,opt,name=digital_signature,json=digitalSignature,proto3" json:"digital_signature,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *DeactivateVPARequest) Reset() {
	*x = DeactivateVPARequest{}
	mi := &file_proto_upi_core_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeactivateVPARequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeactivateVPARequest) ProtoMessage() {}

func (x *DeactivateVPARequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_upi_core_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeactivateVPARequest.ProtoReflect.Descriptor instead.
func (*DeactivateVPARequest) Descriptor() ([]byte, []int) {
	return file_proto_upi_core_proto_rawDescGZIP(), []int{16}
}

func (x *DeactivateVPARequest) GetVpa() string {
	if x != nil {
		return x.Vpa
	}
	return ""
}

func (x *DeactivateVPARequest) GetBankCode() string {
	if x != nil {
		return x.BankCode
	}
	return ""
}

func (x *DeactivateVPARequest) GetDigitalSignature() string {
	if x != nil {
		return x.DigitalSignature
	}
	return ""
}

type DeactivateVPAResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	ErrorCode     string                 `protobuf:"bytes,2,opt,name=error_code,json=errorCode,proto3" json:"error_code,omitempty"`
	ErrorMessage  string                 `protobuf:"bytes,3,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	DeactivatedAt *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=deactivated_at,json=deactivatedAt,proto3" json:"deactivated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeactivateVPAResponse) Reset() {
	*x = DeactivateVPAResponse{}
	mi := &file_proto_upi_core_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeactivateVPAResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeactivateVPAResponse) ProtoMessage() {}

func (x *DeactivateVPAResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_upi_core_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeactivateVPAResponse.ProtoReflect.Descriptor instead.
func (*DeactivateVPAResponse) Descriptor() ([]byte, []int) {
	return file_proto_upi_core_proto_rawDescGZIP(), []int{17}
}

func (x *DeactivateVPAResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *DeactivateVPAResponse) GetErrorCode() string {
	if x != nil {
		return x.ErrorCode
	}
	return ""
}

func (x *DeactivateVPAResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

func (x *DeactivateVPAResponse) GetDeactivatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.DeactivatedAt
	}
	return nil
}

// Health and Monitoring Messages
type HealthCheckRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthCheckRequest) Reset() {
	*x = HealthCheckRequest{}
	mi := &file_proto_upi_core_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthCheckRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthCheckRequest) ProtoMessage() {}

func (x *HealthCheckRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_upi_core_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthCheckRequest.ProtoReflect.Descriptor instead.
func (*HealthCheckRequest) Descriptor() ([]byte, []int) {
	return file_proto_upi_core_proto_rawDescGZIP(), []int{18}
}

type HealthCheckResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Version       string                 `protobuf:"bytes,3,opt,name=version,proto3" json:"version,omitempty"`
	Uptime        string                 `protobuf:"bytes,4,opt,name=uptime,proto3" json:"uptime,omitempty"`
	Dependencies  map[string]string      `protobuf:"bytes,5,rep,name=dependencies,proto3" json:"dependencies,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthCheckResponse) Reset() {
	*x = HealthCheckResponse{}
	mi := &file_proto_upi_core_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthCheckResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthCheckResponse) ProtoMessage() {}

func (x *HealthCheckResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_upi_core_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthCheckResponse.ProtoReflect.Descriptor instead.
func (*HealthCheckResponse) Descriptor() ([]byte, []int) {
	return file_proto_upi_core_proto_rawDescGZIP(), []int{19}
}

func (x *HealthCheckResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *HealthCheckResponse) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *HealthCheckResponse) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *HealthCheckResponse) GetUptime() string {
	if x != nil {
		return x.Uptime
	}
	return ""
}

func (x *HealthCheckResponse) GetDependencies() map[string]string {
	if x != nil {
		return x.Dependencies
	}
	return nil
}

type MetricsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MetricsRequest) Reset() {
	*x = MetricsRequest{}
	mi := &file_proto_upi_core_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MetricsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MetricsRequest) ProtoMessage() {}

func (x *MetricsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_upi_core_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MetricsRequest.ProtoReflect.Descriptor instead.
func (*MetricsRequest) Descriptor() ([]byte, []int) {
	return file_proto_upi_core_proto_rawDescGZIP(), []int{20}
}

type MetricsResponse struct {
	state                  protoimpl.MessageState `protogen:"open.v1"`
	TotalTransactions      int64                  `protobuf:"varint,1,opt,name=total_transactions,json=totalTransactions,proto3" json:"total_transactions,omitempty"`
	SuccessfulTransactions int64                  `protobuf:"varint,2,opt,name=successful_transactions,json=successfulTransactions,proto3" json:"successful_transactions,omitempty"`
	FailedTransactions     int64                  `protobuf:"varint,3,opt,name=failed_transactions,json=failedTransactions,proto3" json:"failed_transactions,omitempty"`
	SuccessRatePercent     float64                `protobuf:"fixed64,4,opt,name=success_rate_percent,json=successRatePercent,proto3" json:"success_rate_percent,omitempty"`
	AvgProcessingTimeMs    int64                  `protobuf:"varint,5,opt,name=avg_processing_time_ms,json=avgProcessingTimeMs,proto3" json:"avg_processing_time_ms,omitempty"`
	BankHealthScores       map[string]int64       `protobuf:"bytes,6,rep,name=bank_health_scores,json=bankHealthScores,proto3" json:"bank_health_scores,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *MetricsResponse) Reset() {
	*x = MetricsResponse{}
	mi := &file_proto_upi_core_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MetricsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MetricsResponse) ProtoMessage() {}

func (x *MetricsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_upi_core_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MetricsResponse.ProtoReflect.Descriptor instead.
func (*MetricsResponse) Descriptor() ([]byte, []int) {
	return file_proto_upi_core_proto_rawDescGZIP(), []int{21}
}

func (x *MetricsResponse) GetTotalTransactions() int64 {
	if x != nil {
		return x.TotalTransactions
	}
	return 0
}

func (x *MetricsResponse) GetSuccessfulTransactions() int64 {
	if x != nil {
		return x.SuccessfulTransactions
	}
	return 0
}

func (x *MetricsResponse) GetFailedTransactions() int64 {
	if x != nil {
		return x.FailedTransactions
	}
	return 0
}

func (x *MetricsResponse) GetSuccessRatePercent() float64 {
	if x != nil {
		return x.SuccessRatePercent
	}
	return 0
}

func (x *MetricsResponse) GetAvgProcessingTimeMs() int64 {
	if x != nil {
		return x.AvgProcessingTimeMs
	}
	return 0
}

func (x *MetricsResponse) GetBankHealthScores() map[string]int64 {
	if x != nil {
		return x.BankHealthScores
	}
	return nil
}

var File_proto_upi_core_proto protoreflect.FileDescriptor

const file_proto_upi_core_proto_rawDesc = "" +
	"\n" +
	"\x14proto/upi_core.proto\x12\bupi.core\x1a\x1fgoogle/protobuf/timestamp.proto\"\xa1\x03\n" +
	"\x12TransactionRequest\x12%\n" +
	"\x0etransaction_id\x18\x01 \x01(\tR\rtransactionId\x12\x1b\n" +
	"\tpayer_vpa\x18\x02 \x01(\tR\bpayerVpa\x12\x1b\n" +
	"\tpayee_vpa\x18\x03 \x01(\tR\bpayeeVpa\x12!\n" +
	"\famount_paisa\x18\x04 \x01(\x03R\vamountPaisa\x12-\n" +
	"\x04type\x18\x05 \x01(\x0e2\x19.upi.core.TransactionTypeR\x04type\x12\x1c\n" +
	"\treference\x18\x06 \x01(\tR\treference\x12&\n" +
	"\x0fpayer_bank_code\x18\a \x01(\tR\rpayerBankCode\x12&\n" +
	"\x0fpayee_bank_code\x18\b \x01(\tR\rpayeeBankCode\x12+\n" +
	"\x11digital_signature\x18\t \x01(\tR\x10digitalSignature\x12=\n" +
	"\finitiated_at\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampR\vinitiatedAt\"\xaa\x03\n" +
	"\x13TransactionResponse\x12%\n" +
	"\x0etransaction_id\x18\x01 \x01(\tR\rtransactionId\x12\x10\n" +
	"\x03rrn\x18\x02 \x01(\tR\x03rrn\x123\n" +
	"\x06status\x18\x03 \x01(\x0e2\x1b.upi.core.TransactionStatusR\x06status\x12&\n" +
	"\x0fpayer_bank_code\x18\x04 \x01(\tR\rpayerBankCode\x12&\n" +
	"\x0fpayee_bank_code\x18\x05 \x01(\tR\rpayeeBankCode\x12-\n" +
	"\x04fees\x18\x06 \x01(\v2\x19.upi.core.TransactionFeesR\x04fees\x12#\n" +
	"\rsettlement_id\x18\a \x01(\tR\fsettlementId\x12\x1d\n" +
	"\n" +
	"error_code\x18\b \x01(\tR\terrorCode\x12#\n" +
	"\rerror_message\x18\t \x01(\tR\ferrorMessage\x12=\n" +
	"\fprocessed_at\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampR\vprocessedAt\"\x88\x01\n" +
	"\x0fTransactionFees\x120\n" +
	"\x14processing_fee_paisa\x18\x01 \x01(\x03R\x12processingFeePaisa\x12\x1b\n" +
	"\tgst_paisa\x18\x02 \x01(\x03R\bgstPaisa\x12&\n" +
	"\x0ftotal_fee_paisa\x18\x03 \x01(\x03R\rtotalFeePaisa\"^\n" +
	"\x18TransactionStatusRequest\x12%\n" +
	"\x0etransaction_id\x18\x01 \x01(\tR\rtransactionId\x12\x1b\n" +
	"\tbank_code\x18\x02 \x01(\tR\bbankCode\"\x90\x03\n" +
	"\x19TransactionStatusResponse\x12%\n" +
	"\x0etransaction_id\x18\x01 \x01(\tR\rtransactionId\x12\x10\n" +
	"\x03rrn\x18\x02 \x01(\tR\x03rrn\x123\n" +
	"\x06status\x18\x03 \x01(\x0e2\x1b.upi.core.TransactionStatusR\x06status\x122\n" +
	"\x06events\x18\x04 \x03(\v2\x1a.upi.core.TransactionEventR\x06events\x12!\n" +
	"\famount_paisa\x18\x05 \x01(\x03R\vamountPaisa\x12\x1b\n" +
	"\tpayer_vpa\x18\x06 \x01(\tR\bpayerVpa\x12\x1b\n" +
	"\tpayee_vpa\x18\a \x01(\tR\bpayeeVpa\x129\n" +
	"\n" +
	"created_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"\xa3\x01\n" +
	"\x10TransactionEvent\x128\n" +
	"\ttimestamp\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\x123\n" +
	"\x06status\x18\x02 \x01(\x0e2\x1b.upi.core.TransactionStatusR\x06status\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\"\xa3\x01\n" +
	"\x18CancelTransactionRequest\x12%\n" +
	"\x0etransaction_id\x18\x01 \x01(\tR\rtransactionId\x12\x1b\n" +
	"\tbank_code\x18\x02 \x01(\tR\bbankCode\x12\x16\n" +
	"\x06reason\x18\x03 \x01(\tR\x06reason\x12+\n" +
	"\x11digital_signature\x18\x04 \x01(\tR\x10digitalSignature\"\xb8\x01\n" +
	"\x19CancelTransactionResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x1d\n" +
	"\n" +
	"error_code\x18\x02 \x01(\tR\terrorCode\x12#\n" +
	"\rerror_message\x18\x03 \x01(\tR\ferrorMessage\x12=\n" +
	"\fcancelled_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\vcancelledAt\"\xed\x01\n" +
	"\x19ReverseTransactionRequest\x126\n" +
	"\x17original_transaction_id\x18\x01 \x01(\tR\x15originalTransactionId\x126\n" +
	"\x17reversal_transaction_id\x18\x02 \x01(\tR\x15reversalTransactionId\x12\x1b\n" +
	"\tbank_code\x18\x03 \x01(\tR\bbankCode\x12\x16\n" +
	"\x06reason\x18\x04 \x01(\tR\x06reason\x12+\n" +
	"\x11digital_signature\x18\x05 \x01(\tR\x10digitalSignature\"\xda\x01\n" +
	"\x1aReverseTransactionResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12!\n" +
	"\freversal_rrn\x18\x02 \x01(\tR\vreversalRrn\x12\x1d\n" +
	"\n" +
	"error_code\x18\x03 \x01(\tR\terrorCode\x12#\n" +
	"\rerror_message\x18\x04 \x01(\tR\ferrorMessage\x12;\n" +
	"\vreversed_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"reversedAt\"W\n" +
	"\x11ResolveVPARequest\x12\x10\n" +
	"\x03vpa\x18\x01 \x01(\tR\x03vpa\x120\n" +
	"\x14requesting_bank_code\x18\x02 \x01(\tR\x12requestingBankCode\"\x81\x02\n" +
	"\x12ResolveVPAResponse\x12\x16\n" +
	"\x06exists\x18\x01 \x01(\bR\x06exists\x12\x1b\n" +
	"\tbank_code\x18\x02 \x01(\tR\bbankCode\x12%\n" +
	"\x0eaccount_number\x18\x03 \x01(\tR\raccountNumber\x12.\n" +
	"\x13account_holder_name\x18\x04 \x01(\tR\x11accountHolderName\x12\x1b\n" +
	"\tis_active\x18\x05 \x01(\bR\bisActive\x12\x1d\n" +
	"\n" +
	"error_code\x18\x06 \x01(\tR\terrorCode\x12#\n" +
	"\rerror_message\x18\a \x01(\tR\ferrorMessage\"\xec\x01\n" +
	"\x12RegisterVPARequest\x12\x10\n" +
	"\x03vpa\x18\x01 \x01(\tR\x03vpa\x12\x1b\n" +
	"\tbank_code\x18\x02 \x01(\tR\bbankCode\x12%\n" +
	"\x0eaccount_number\x18\x03 \x01(\tR\raccountNumber\x12.\n" +
	"\x13account_holder_name\x18\x04 \x01(\tR\x11accountHolderName\x12#\n" +
	"\rmobile_number\x18\x05 \x01(\tR\fmobileNumber\x12+\n" +
	"\x11digital_signature\x18\x06 \x01(\tR\x10digitalSignature\"\xcb\x01\n" +
	"\x13RegisterVPAResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x15\n" +
	"\x06vpa_id\x18\x02 \x01(\tR\x05vpaId\x12\x1d\n" +
	"\n" +
	"error_code\x18\x03 \x01(\tR\terrorCode\x12#\n" +
	"\rerror_message\x18\x04 \x01(\tR\ferrorMessage\x12?\n" +
	"\rregistered_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\fregisteredAt\"\x9c\x01\n" +
	"\x10UpdateVPARequest\x12\x10\n" +
	"\x03vpa\x18\x01 \x01(\tR\x03vpa\x12\x1b\n" +
	"\tbank_code\x18\x02 \x01(\tR\bbankCode\x12,\n" +
	"\x12new_account_number\x18\x03 \x01(\tR\x10newAccountNumber\x12+\n" +
	"\x11digital_signature\x18\x04 \x01(\tR\x10digitalSignature\"\xac\x01\n" +
	"\x11UpdateVPAResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x1d\n" +
	"\n" +
	"error_code\x18\x02 \x01(\tR\terrorCode\x12#\n" +
	"\rerror_message\x18\x03 \x01(\tR\ferrorMessage\x129\n" +
	"\n" +
	"updated_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"r\n" +
	"\x14DeactivateVPARequest\x12\x10\n" +
	"\x03vpa\x18\x01 \x01(\tR\x03vpa\x12\x1b\n" +
	"\tbank_code\x18\x02 \x01(\tR\bbankCode\x12+\n" +
	"\x11digital_signature\x18\x03 \x01(\tR\x10digitalSignature\"\xb8\x01\n" +
	"\x15DeactivateVPAResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x1d\n" +
	"\n" +
	"error_code\x18\x02 \x01(\tR\terrorCode\x12#\n" +
	"\rerror_message\x18\x03 \x01(\tR\ferrorMessage\x12A\n" +
	"\x0edeactivated_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\rdeactivatedAt\"\x14\n" +
	"\x12HealthCheckRequest\"\xaf\x02\n" +
	"\x13HealthCheckResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x128\n" +
	"\ttimestamp\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\x12\x18\n" +
	"\aversion\x18\x03 \x01(\tR\aversion\x12\x16\n" +
	"\x06uptime\x18\x04 \x01(\tR\x06uptime\x12S\n" +
	"\fdependencies\x18\x05 \x03(\v2/.upi.core.HealthCheckResponse.DependenciesEntryR\fdependencies\x1a?\n" +
	"\x11DependenciesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x10\n" +
	"\x0eMetricsRequest\"\xb5\x03\n" +
	"\x0fMetricsResponse\x12-\n" +
	"\x12total_transactions\x18\x01 \x01(\x03R\x11totalTransactions\x127\n" +
	"\x17successful_transactions\x18\x02 \x01(\x03R\x16successfulTransactions\x12/\n" +
	"\x13failed_transactions\x18\x03 \x01(\x03R\x12failedTransactions\x120\n" +
	"\x14success_rate_percent\x18\x04 \x01(\x01R\x12successRatePercent\x123\n" +
	"\x16avg_processing_time_ms\x18\x05 \x01(\x03R\x13avgProcessingTimeMs\x12]\n" +
	"\x12bank_health_scores\x18\x06 \x03(\v2/.upi.core.MetricsResponse.BankHealthScoresEntryR\x10bankHealthScores\x1aC\n" +
	"\x15BankHealthScoresEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x03R\x05value:\x028\x01*\x9e\x01\n" +
	"\x0fTransactionType\x12 \n" +
	"\x1cTRANSACTION_TYPE_UNSPECIFIED\x10\x00\x12\x18\n" +
	"\x14TRANSACTION_TYPE_P2P\x10\x01\x12\x18\n" +
	"\x14TRANSACTION_TYPE_P2M\x10\x02\x12\x18\n" +
	"\x14TRANSACTION_TYPE_M2P\x10\x03\x12\x1b\n" +
	"\x17TRANSACTION_TYPE_REFUND\x10\x04*\xf9\x01\n" +
	"\x11TransactionStatus\x12\"\n" +
	"\x1eTRANSACTION_STATUS_UNSPECIFIED\x10\x00\x12\x1e\n" +
	"\x1aTRANSACTION_STATUS_PENDING\x10\x01\x12\x1e\n" +
	"\x1aTRANSACTION_STATUS_SUCCESS\x10\x02\x12\x1d\n" +
	"\x19TRANSACTION_STATUS_FAILED\x10\x03\x12\x1e\n" +
	"\x1aTRANSACTION_STATUS_TIMEOUT\x10\x04\x12 \n" +
	"\x1cTRANSACTION_STATUS_CANCELLED\x10\x05\x12\x1f\n" +
	"\x1bTRANSACTION_STATUS_REVERSED\x10\x062\xb8\x06\n" +
	"\aUpiCore\x12Q\n" +
	"\x12ProcessTransaction\x12\x1c.upi.core.TransactionRequest\x1a\x1d.upi.core.TransactionResponse\x12_\n" +
	"\x14GetTransactionStatus\x12\".upi.core.TransactionStatusRequest\x1a#.upi.core.TransactionStatusResponse\x12\\\n" +
	"\x11CancelTransaction\x12\".upi.core.CancelTransactionRequest\x1a#.upi.core.CancelTransactionResponse\x12_\n" +
	"\x12ReverseTransaction\x12#.upi.core.ReverseTransactionRequest\x1a$.upi.core.ReverseTransactionResponse\x12G\n" +
	"\n" +
	"ResolveVPA\x12\x1b.upi.core.ResolveVPARequest\x1a\x1c.upi.core.ResolveVPAResponse\x12J\n" +
	"\vRegisterVPA\x12\x1c.upi.core.RegisterVPARequest\x1a\x1d.upi.core.RegisterVPAResponse\x12D\n" +
	"\tUpdateVPA\x12\x1a.upi.core.UpdateVPARequest\x1a\x1b.upi.core.UpdateVPAResponse\x12P\n" +
	"\rDeactivateVPA\x12\x1e.upi.core.DeactivateVPARequest\x1a\x1f.upi.core.DeactivateVPAResponse\x12J\n" +
	"\vHealthCheck\x12\x1c.upi.core.HealthCheckRequest\x1a\x1d.upi.core.HealthCheckResponse\x12A\n" +
	"\n" +
	"GetMetrics\x12\x18.upi.core.MetricsRequest\x1a\x19.upi.core.MetricsResponseB,Z*github.com/suuupra/payments/proto/upi_coreb\x06proto3"

var (
	file_proto_upi_core_proto_rawDescOnce sync.Once
	file_proto_upi_core_proto_rawDescData []byte
)

func file_proto_upi_core_proto_rawDescGZIP() []byte {
	file_proto_upi_core_proto_rawDescOnce.Do(func() {
		file_proto_upi_core_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_upi_core_proto_rawDesc), len(file_proto_upi_core_proto_rawDesc)))
	})
	return file_proto_upi_core_proto_rawDescData
}

var file_proto_upi_core_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_proto_upi_core_proto_msgTypes = make([]protoimpl.MessageInfo, 24)
var file_proto_upi_core_proto_goTypes = []any{
	(TransactionType)(0),               // 0: upi.core.TransactionType
	(TransactionStatus)(0),             // 1: upi.core.TransactionStatus
	(*TransactionRequest)(nil),         // 2: upi.core.TransactionRequest
	(*TransactionResponse)(nil),        // 3: upi.core.TransactionResponse
	(*TransactionFees)(nil),            // 4: upi.core.TransactionFees
	(*TransactionStatusRequest)(nil),   // 5: upi.core.TransactionStatusRequest
	(*TransactionStatusResponse)(nil),  // 6: upi.core.TransactionStatusResponse
	(*TransactionEvent)(nil),           // 7: upi.core.TransactionEvent
	(*CancelTransactionRequest)(nil),   // 8: upi.core.CancelTransactionRequest
	(*CancelTransactionResponse)(nil),  // 9: upi.core.CancelTransactionResponse
	(*ReverseTransactionRequest)(nil),  // 10: upi.core.ReverseTransactionRequest
	(*ReverseTransactionResponse)(nil), // 11: upi.core.ReverseTransactionResponse
	(*ResolveVPARequest)(nil),          // 12: upi.core.ResolveVPARequest
	(*ResolveVPAResponse)(nil),         // 13: upi.core.ResolveVPAResponse
	(*RegisterVPARequest)(nil),         // 14: upi.core.RegisterVPARequest
	(*RegisterVPAResponse)(nil),        // 15: upi.core.RegisterVPAResponse
	(*UpdateVPARequest)(nil),           // 16: upi.core.UpdateVPARequest
	(*UpdateVPAResponse)(nil),          // 17: upi.core.UpdateVPAResponse
	(*DeactivateVPARequest)(nil),       // 18: upi.core.DeactivateVPARequest
	(*DeactivateVPAResponse)(nil),      // 19: upi.core.DeactivateVPAResponse
	(*HealthCheckRequest)(nil),         // 20: upi.core.HealthCheckRequest
	(*HealthCheckResponse)(nil),        // 21: upi.core.HealthCheckResponse
	(*MetricsRequest)(nil),             // 22: upi.core.MetricsRequest
	(*MetricsResponse)(nil),            // 23: upi.core.MetricsResponse
	nil,                                // 24: upi.core.HealthCheckResponse.DependenciesEntry
	nil,                                // 25: upi.core.MetricsResponse.BankHealthScoresEntry
	(*timestamppb.Timestamp)(nil),      // 26: google.protobuf.Timestamp
}
var file_proto_upi_core_proto_depIdxs = []int32{
	0,  // 0: upi.core.TransactionRequest.type:type_name -> upi.core.TransactionType
	26, // 1: upi.core.TransactionRequest.initiated_at:type_name -> google.protobuf.Timestamp
	1,  // 2: upi.core.TransactionResponse.status:type_name -> upi.core.TransactionStatus
	4,  // 3: upi.core.TransactionResponse.fees:type_name -> upi.core.TransactionFees
	26, // 4: upi.core.TransactionResponse.processed_at:type_name -> google.protobuf.Timestamp
	1,  // 5: upi.core.TransactionStatusResponse.status:type_name -> upi.core.TransactionStatus
	7,  // 6: upi.core.TransactionStatusResponse.events:type_name -> upi.core.TransactionEvent
	26, // 7: upi.core.TransactionStatusResponse.created_at:type_name -> google.protobuf.Timestamp
	26, // 8: upi.core.TransactionStatusResponse.updated_at:type_name -> google.protobuf.Timestamp
	26, // 9: upi.core.TransactionEvent.timestamp:type_name -> google.protobuf.Timestamp
	1,  // 10: upi.core.TransactionEvent.status:type_name -> upi.core.TransactionStatus
	26, // 11: upi.core.CancelTransactionResponse.cancelled_at:type_name -> google.protobuf.Timestamp
	26, // 12: upi.core.ReverseTransactionResponse.reversed_at:type_name -> google.protobuf.Timestamp
	26, // 13: upi.core.RegisterVPAResponse.registered_at:type_name -> google.protobuf.Timestamp
	26, // 14: upi.core.UpdateVPAResponse.updated_at:type_name -> google.protobuf.Timestamp
	26, // 15: upi.core.DeactivateVPAResponse.deactivated_at:type_name -> google.protobuf.Timestamp
	26, // 16: upi.core.HealthCheckResponse.timestamp:type_name -> google.protobuf.Timestamp
	24, // 17: upi.core.HealthCheckResponse.dependencies:type_name -> upi.core.HealthCheckResponse.DependenciesEntry
	25, // 18: upi.core.MetricsResponse.bank_health_scores:type_name -> upi.core.MetricsResponse.BankHealthScoresEntry
	2,  // 19: upi.core.UpiCore.ProcessTransaction:input_type -> upi.core.TransactionRequest
	5,  // 20: upi.core.UpiCore.GetTransactionStatus:input_type -> upi.core.TransactionStatusRequest
	8,  // 21: upi.core.UpiCore.CancelTransaction:input_type -> upi.core.CancelTransactionRequest
	10, // 22: upi.core.UpiCore.ReverseTransaction:input_type -> upi.core.ReverseTransactionRequest
	12, // 23: upi.core.UpiCore.ResolveVPA:input_type -> upi.core.ResolveVPARequest
	14, // 24: upi.core.UpiCore.RegisterVPA:input_type -> upi.core.RegisterVPARequest
	16, // 25: upi.core.UpiCore.UpdateVPA:input_type -> upi.core.UpdateVPARequest
	18, // 26: upi.core.UpiCore.DeactivateVPA:input_type -> upi.core.DeactivateVPARequest
	20, // 27: upi.core.UpiCore.HealthCheck:input_type -> upi.core.HealthCheckRequest
	22, // 28: upi.core.UpiCore.GetMetrics:input_type -> upi.core.MetricsRequest
	3,  // 29: upi.core.UpiCore.ProcessTransaction:output_type -> upi.core.TransactionResponse
	6,  // 30: upi.core.UpiCore.GetTransactionStatus:output_type -> upi.core.TransactionStatusResponse
	9,  // 31: upi.core.UpiCore.CancelTransaction:output_type -> upi.core.CancelTransactionResponse
	11, // 32: upi.core.UpiCore.ReverseTransaction:output_type -> upi.core.ReverseTransactionResponse
	13, // 33: upi.core.UpiCore.ResolveVPA:output_type -> upi.core.ResolveVPAResponse
	15, // 34: upi.core.UpiCore.RegisterVPA:output_type -> upi.core.RegisterVPAResponse
	17, // 35: upi.core.UpiCore.UpdateVPA:output_type -> upi.core.UpdateVPAResponse
	19, // 36: upi.core.UpiCore.DeactivateVPA:output_type -> upi.core.DeactivateVPAResponse
	21, // 37: upi.core.UpiCore.HealthCheck:output_type -> upi.core.HealthCheckResponse
	23, // 38: upi.core.UpiCore.GetMetrics:output_type -> upi.core.MetricsResponse
	29, // [29:39] is the sub-list for method output_type
	19, // [19:29] is the sub-list for method input_type
	19, // [19:19] is the sub-list for extension type_name
	19, // [19:19] is the sub-list for extension extendee
	0,  // [0:19] is the sub-list for field type_name
}

func init() { file_proto_upi_core_proto_init() }
func file_proto_upi_core_proto_init() {
	if File_proto_upi_core_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_upi_core_proto_rawDesc), len(file_proto_upi_core_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   24,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_upi_core_proto_goTypes,
		DependencyIndexes: file_proto_upi_core_proto_depIdxs,
		EnumInfos:         file_proto_upi_core_proto_enumTypes,
		MessageInfos:      file_proto_upi_core_proto_msgTypes,
	}.Build()
	File_proto_upi_core_proto = out.File
	file_proto_upi_core_proto_goTypes = nil
	file_proto_upi_core_proto_depIdxs = nil
}
