version: '4'

services:
  # Payments Service - Transaction Processing
  payments:
    build:
      context: .
      dockerfile: Dockerfile
      target: production
    container_name: suuupra-payments
    restart: unless-stopped
    ports:
      - "8082:8082"   # Main service port (aligned with main compose)
      - "9093:9093"   # Metrics port (aligned with main compose)
    environment:
      # Core configuration (aligned with main docker-compose.yml)
      NODE_ENV: production
      PORT: 8082
      METRICS_PORT: 9093
      
      # Database - Using main infrastructure PostgreSQL
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres123}
      POSTGRES_DATABASE: payments
      POSTGRES_POOL_MAX: 25  # Higher pool for payment processing
      
      # Redis for idempotency - Using main infrastructure
      REDIS_HOST: redis
      REDIS_PORT: 6379
      REDIS_IDEMPOTENCY_PREFIX: "idem:"
      REDIS_IDEMPOTENCY_TTL: 86400  # 24 hours
      
      # Event streaming - Using main infrastructure Kafka
      KAFKA_BROKERS: kafka:29092
      KAFKA_CLIENT_ID: payments-service
      KAFKA_GROUP_ID: payments-consumers
      KAFKA_PAYMENT_EVENTS_TOPIC: payment.events
      KAFKA_ORDER_EVENTS_TOPIC: order.events
      
      # Security & Vault - Using main infrastructure
      VAULT_ADDR: http://vault:8200
      VAULT_TOKEN: ${VAULT_TOKEN:-myroot}
      VAULT_MOUNT_PATH: payments
      
      # Payment gateways (secrets from Vault)
      STRIPE_WEBHOOK_SECRET: ${STRIPE_WEBHOOK_SECRET:-}
      RAZORPAY_KEY_SECRET: ${RAZORPAY_KEY_SECRET:-}
      
      # UPI Core integration (use actual service, not mock)
      UPI_CORE_URL: http://upi-core:8087
      
      # Observability - Using main infrastructure
      OTEL_SERVICE_NAME: payments-service
      OTEL_SERVICE_VERSION: 1.0.0
      OTEL_EXPORTER_OTLP_ENDPOINT: http://otel-collector:4317
      OTEL_RESOURCE_ATTRIBUTES: service.namespace=suuupra,deployment.environment=docker-compose
      
      # Performance & reliability
      PAYMENT_TIMEOUT_MS: 30000
      MAX_RETRY_ATTEMPTS: 3
      CIRCUIT_BREAKER_THRESHOLD: 10
      IDEMPOTENCY_TTL_HOURS: 24
      WEBHOOK_TIMEOUT_SECONDS: 30
      MAX_WEBHOOK_RETRIES: 5
      
    volumes:
      - app_logs:/app/logs
    
    # Use main infrastructure services (no separate dependencies)
    external_links:
      - postgres:postgres
      - redis:redis
      - kafka:kafka
      - vault:vault
      - upi-core:upi-core
      - otel-collector:otel-collector
    
    networks:
      - suuupra-network
    
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8082/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 60s
    
    labels:
      - "prometheus.scrape=true"
      - "prometheus.port=9093"

# ===================================================================
# VOLUMES - Aligned with main infrastructure
# ===================================================================
volumes:
  app_logs:
    external: true
    name: suuupra_app_logs

# ===================================================================
# NETWORKS - Using main infrastructure network
# ===================================================================
networks:
  suuupra-network:
    external: true
    name: suuupra-network

# ===================================================================
# NOTES:
# - All infrastructure services (PostgreSQL, Redis, Kafka, Vault, 
#   Prometheus, Grafana, Jaeger) are provided by main infrastructure
# - UPI Core service is now a real microservice, not a mock
# - Use: docker-compose -f ../../docker-compose.infrastructure.yml up -d
# - Then: docker-compose -f docker-compose.yml up -d
# ===================================================================