name: CI

on:
  pull_request:
  push:
    branches: [ main ]

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Cache Maven
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
      - name: Build & test Identity (no integration)
        run: |
          cd services/identity
          ./mvnw -B -DskipITs clean verify | cat
      - name: Lint Gateway
        run: |
          cd services/api-gateway
          npm ci
          npm run lint | cat

  security-scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Nancy (Go vuln scan) placeholder
        run: echo "Run SAST/DAST tools here"


