creator_studio:
  app_name: "Suuupra Creator Studio"
  version: "1.0.0"
  port: 3004
  environment: ${NODE_ENV:development}

database:
  mongodb:
    uri: ${MONGODB_URI:mongodb://localhost:27017/creator_studio}
    pool_size: 10
    timeout_ms: 5000
  
  postgres:
    host: ${POSTGRES_HOST:localhost}
    port: ${POSTGRES_PORT:5432}
    database: ${POSTGRES_DB:creator_analytics}
    username: ${POSTGRES_USER:creator}
    password: ${POSTGRES_PASSWORD:creator123}

storage:
  s3:
    bucket: ${S3_BUCKET:suuupra-creator-content}
    region: ${AWS_REGION:us-east-1}
    access_key: ${AWS_ACCESS_KEY:}
    secret_key: ${AWS_SECRET_KEY:}
  
  max_file_size_mb: 500
  allowed_formats:
    video: ["mp4", "mov", "avi", "mkv"]
    image: ["jpg", "jpeg", "png", "gif", "webp"]
    audio: ["mp3", "wav", "aac", "flac"]

redis:
  host: ${REDIS_HOST:localhost}
  port: ${REDIS_PORT:6379}
  password: ${REDIS_PASSWORD:}
  db: 4

transcoding:
  ffmpeg_path: ${FFMPEG_PATH:/usr/local/bin/ffmpeg}
  quality_presets:
    - name: "720p"
      resolution: "1280x720"
      bitrate: "2500k"
    - name: "1080p"
      resolution: "1920x1080"
      bitrate: "5000k"
  
  thumbnail_count: 3
  hls_segment_duration: 10

analytics:
  track_events:
    - upload_start
    - upload_complete
    - transcode_complete
    - view_count
    - engagement_metrics

authentication:
  jwt_secret: ${JWT_SECRET:creator-super-secret-key}
  token_expiry: "2h"

logging:
  level: ${LOG_LEVEL:info}
  format: json
  output: console

monitoring:
  health_check_path: "/health"
  metrics_path: "/metrics"